#!/system/bin/sh
##########################################################################################
# Zapret2 Magisk Module - Action Menu (Volume Key Selection)
##########################################################################################

MODDIR="${0%/*}"
ZAPRET_DIR="$MODDIR/zapret2"
CONFIG="$ZAPRET_DIR/config.sh"
STRATEGIES_DIR="$ZAPRET_DIR/strategies"

# Colors
R='\033[0;31m'
G='\033[0;32m'
Y='\033[0;33m'
B='\033[0;34m'
P='\033[0;35m'
C='\033[0;36m'
W='\033[0;37m'
N='\033[0m'

##########################################################################################
# Volume Key Selection Functions
##########################################################################################

# Key event reader
get_key_event() {
    local key=""
    while true; do
        key=$(timeout 10 getevent -lc 1 2>/dev/null | grep KEY_ | head -1 | awk '{print $3}')
        case "$key" in
            KEY_VOLUMEUP)   return 0 ;;  # UP = Select/Next
            KEY_VOLUMEDOWN) return 1 ;;  # DOWN = Previous/Back
            KEY_POWER)      return 2 ;;  # POWER = Confirm
        esac
    done
}

# Print option with highlight
print_option() {
    local selected=$1
    local current=$2
    local text=$3
    local color=$4

    if [ "$selected" = "$current" ]; then
        echo -e "  ${G}► ${color}${text}${N} ◄"
    else
        echo -e "    ${color}${text}${N}"
    fi
}

# Generic menu selector
select_menu() {
    local title=$1
    shift
    local options=("$@")
    local selected=0
    local count=${#options[@]}

    while true; do
        clear
        echo -e "${C}╔══════════════════════════════════════════╗${N}"
        echo -e "${C}║${W}     ZAPRET2 DPI BYPASS CONFIGURATOR     ${C}║${N}"
        echo -e "${C}╠══════════════════════════════════════════╣${N}"
        echo -e "${C}║${Y} $title${C}║${N}"
        echo -e "${C}╚══════════════════════════════════════════╝${N}"
        echo ""

        local i=0
        for opt in "${options[@]}"; do
            print_option $selected $i "$opt" "$W"
            i=$((i + 1))
        done

        echo ""
        echo -e "${B}[VOL+]${N} Next  ${B}[VOL-]${N} Prev  ${B}[POWER]${N} Select"

        get_key_event
        local key=$?

        case $key in
            0) # VOL UP - next
                selected=$((selected + 1))
                [ $selected -ge $count ] && selected=0
                ;;
            1) # VOL DOWN - prev
                selected=$((selected - 1))
                [ $selected -lt 0 ] && selected=$((count - 1))
                ;;
            2) # POWER - select
                echo $selected
                return $selected
                ;;
        esac
    done
}

##########################################################################################
# Strategy Categories
##########################################################################################

# YouTube strategies
YOUTUBE_STRATEGIES=(
    "syndata_7_tls_google_multisplit_midsld|YouTube Default (syndata+multisplit)"
    "censorliber_google_syndata|Censorliber Google + Syndata"
    "censorliber_google_syndata_v2|Censorliber v2 (tls_mod)"
    "censorliber_google_syndata_tcpack|Censorliber + TCP ACK"
    "alt9|Alt v9 (hostfakesplit)"
    "alt11_100_syndata|Alt v11 + Syndata"
    "none|Disabled"
)

# Discord strategies
DISCORD_STRATEGIES=(
    "syndata_7_tls_google_multisplit_midsld|Discord Default"
    "censorliber_google_syndata|Censorliber Syndata"
    "fake_x6_stun_discord|Voice UDP (STUN fake x6)"
    "none|Disabled"
)

# Telegram strategies
TELEGRAM_STRATEGIES=(
    "syndata_7_tls_google_multisplit_midsld|Telegram Default"
    "censorliber_google_syndata|Censorliber Syndata"
    "none|Disabled"
)

# Other services strategies
OTHER_STRATEGIES=(
    "syndata_7_tls_google_multisplit_midsld|Default Syndata"
    "censorliber_google_syndata|Censorliber"
    "multisplit_split_pos_1|Multisplit Only"
    "other_seqovl|SeqOVL Strategy"
    "none|Disabled"
)

# UDP/QUIC strategies
UDP_STRATEGIES=(
    "fake_x6_quic|QUIC Fake x6"
    "fake_x11_quic|QUIC Fake x11"
    "none|Disabled"
)

##########################################################################################
# Save Configuration
##########################################################################################

save_config() {
    cat > "$CONFIG" << EOF
#!/system/bin/sh
# Zapret2 Configuration - Generated by action.sh
# $(date)

AUTOSTART=1
QNUM=200
DESYNC_MARK=0x40000000
PORTS_TCP="80,443"
PORTS_UDP="443"
PKT_OUT=20
PKT_IN=10
LOG_MODE="android"

# Category Strategies
STRATEGY_YOUTUBE="$STRATEGY_YOUTUBE"
STRATEGY_DISCORD="$STRATEGY_DISCORD"
STRATEGY_TELEGRAM="$STRATEGY_TELEGRAM"
STRATEGY_OTHER="$STRATEGY_OTHER"
STRATEGY_UDP="$STRATEGY_UDP"

# Use category-based configuration
USE_CATEGORIES=1
EOF
    echo -e "${G}Configuration saved!${N}"
}

##########################################################################################
# Load Current Configuration
##########################################################################################

load_config() {
    if [ -f "$CONFIG" ]; then
        . "$CONFIG"
    fi

    # Defaults if not set
    STRATEGY_YOUTUBE="${STRATEGY_YOUTUBE:-syndata_7_tls_google_multisplit_midsld}"
    STRATEGY_DISCORD="${STRATEGY_DISCORD:-syndata_7_tls_google_multisplit_midsld}"
    STRATEGY_TELEGRAM="${STRATEGY_TELEGRAM:-none}"
    STRATEGY_OTHER="${STRATEGY_OTHER:-none}"
    STRATEGY_UDP="${STRATEGY_UDP:-none}"
}

##########################################################################################
# Category Selection Menus
##########################################################################################

select_youtube_strategy() {
    clear
    echo -e "${R}╔══════════════════════════════════════════╗${N}"
    echo -e "${R}║${W}          🎬 YOUTUBE STRATEGY             ${R}║${N}"
    echo -e "${R}╚══════════════════════════════════════════╝${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_YOUTUBE${N}"
    echo ""

    local i=1
    for strat in "${YOUTUBE_STRATEGIES[@]}"; do
        local id=$(echo "$strat" | cut -d'|' -f1)
        local name=$(echo "$strat" | cut -d'|' -f2)
        if [ "$id" = "$STRATEGY_YOUTUBE" ]; then
            echo -e "  ${G}[$i] $name ◄${N}"
        else
            echo -e "  ${W}[$i] $name${N}"
        fi
        i=$((i + 1))
    done

    echo ""
    echo -e "${B}Enter number (1-$((i-1))) or 0 to cancel:${N}"
    read -r choice

    if [ "$choice" -gt 0 ] 2>/dev/null && [ "$choice" -lt "$i" ]; then
        local idx=$((choice - 1))
        STRATEGY_YOUTUBE=$(echo "${YOUTUBE_STRATEGIES[$idx]}" | cut -d'|' -f1)
        echo -e "${G}YouTube strategy set to: $STRATEGY_YOUTUBE${N}"
        sleep 1
    fi
}

select_discord_strategy() {
    clear
    echo -e "${P}╔══════════════════════════════════════════╗${N}"
    echo -e "${P}║${W}          💬 DISCORD STRATEGY             ${P}║${N}"
    echo -e "${P}╚══════════════════════════════════════════╝${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_DISCORD${N}"
    echo ""

    local i=1
    for strat in "${DISCORD_STRATEGIES[@]}"; do
        local id=$(echo "$strat" | cut -d'|' -f1)
        local name=$(echo "$strat" | cut -d'|' -f2)
        if [ "$id" = "$STRATEGY_DISCORD" ]; then
            echo -e "  ${G}[$i] $name ◄${N}"
        else
            echo -e "  ${W}[$i] $name${N}"
        fi
        i=$((i + 1))
    done

    echo ""
    echo -e "${B}Enter number (1-$((i-1))) or 0 to cancel:${N}"
    read -r choice

    if [ "$choice" -gt 0 ] 2>/dev/null && [ "$choice" -lt "$i" ]; then
        local idx=$((choice - 1))
        STRATEGY_DISCORD=$(echo "${DISCORD_STRATEGIES[$idx]}" | cut -d'|' -f1)
        echo -e "${G}Discord strategy set to: $STRATEGY_DISCORD${N}"
        sleep 1
    fi
}

select_telegram_strategy() {
    clear
    echo -e "${C}╔══════════════════════════════════════════╗${N}"
    echo -e "${C}║${W}          ✈️ TELEGRAM STRATEGY            ${C}║${N}"
    echo -e "${C}╚══════════════════════════════════════════╝${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_TELEGRAM${N}"
    echo ""

    local i=1
    for strat in "${TELEGRAM_STRATEGIES[@]}"; do
        local id=$(echo "$strat" | cut -d'|' -f1)
        local name=$(echo "$strat" | cut -d'|' -f2)
        if [ "$id" = "$STRATEGY_TELEGRAM" ]; then
            echo -e "  ${G}[$i] $name ◄${N}"
        else
            echo -e "  ${W}[$i] $name${N}"
        fi
        i=$((i + 1))
    done

    echo ""
    echo -e "${B}Enter number (1-$((i-1))) or 0 to cancel:${N}"
    read -r choice

    if [ "$choice" -gt 0 ] 2>/dev/null && [ "$choice" -lt "$i" ]; then
        local idx=$((choice - 1))
        STRATEGY_TELEGRAM=$(echo "${TELEGRAM_STRATEGIES[$idx]}" | cut -d'|' -f1)
        echo -e "${G}Telegram strategy set to: $STRATEGY_TELEGRAM${N}"
        sleep 1
    fi
}

select_other_strategy() {
    clear
    echo -e "${G}╔══════════════════════════════════════════╗${N}"
    echo -e "${G}║${W}          🌐 OTHER SITES STRATEGY         ${G}║${N}"
    echo -e "${G}╚══════════════════════════════════════════╝${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_OTHER${N}"
    echo ""

    local i=1
    for strat in "${OTHER_STRATEGIES[@]}"; do
        local id=$(echo "$strat" | cut -d'|' -f1)
        local name=$(echo "$strat" | cut -d'|' -f2)
        if [ "$id" = "$STRATEGY_OTHER" ]; then
            echo -e "  ${G}[$i] $name ◄${N}"
        else
            echo -e "  ${W}[$i] $name${N}"
        fi
        i=$((i + 1))
    done

    echo ""
    echo -e "${B}Enter number (1-$((i-1))) or 0 to cancel:${N}"
    read -r choice

    if [ "$choice" -gt 0 ] 2>/dev/null && [ "$choice" -lt "$i" ]; then
        local idx=$((choice - 1))
        STRATEGY_OTHER=$(echo "${OTHER_STRATEGIES[$idx]}" | cut -d'|' -f1)
        echo -e "${G}Other strategy set to: $STRATEGY_OTHER${N}"
        sleep 1
    fi
}

select_udp_strategy() {
    clear
    echo -e "${Y}╔══════════════════════════════════════════╗${N}"
    echo -e "${Y}║${W}          📡 UDP/QUIC STRATEGY            ${Y}║${N}"
    echo -e "${Y}╚══════════════════════════════════════════╝${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_UDP${N}"
    echo ""

    local i=1
    for strat in "${UDP_STRATEGIES[@]}"; do
        local id=$(echo "$strat" | cut -d'|' -f1)
        local name=$(echo "$strat" | cut -d'|' -f2)
        if [ "$id" = "$STRATEGY_UDP" ]; then
            echo -e "  ${G}[$i] $name ◄${N}"
        else
            echo -e "  ${W}[$i] $name${N}"
        fi
        i=$((i + 1))
    done

    echo ""
    echo -e "${B}Enter number (1-$((i-1))) or 0 to cancel:${N}"
    read -r choice

    if [ "$choice" -gt 0 ] 2>/dev/null && [ "$choice" -lt "$i" ]; then
        local idx=$((choice - 1))
        STRATEGY_UDP=$(echo "${UDP_STRATEGIES[$idx]}" | cut -d'|' -f1)
        echo -e "${G}UDP strategy set to: $STRATEGY_UDP${N}"
        sleep 1
    fi
}

##########################################################################################
# Status Display
##########################################################################################

show_status() {
    clear
    echo -e "${C}╔══════════════════════════════════════════╗${N}"
    echo -e "${C}║${W}           ZAPRET2 STATUS                 ${C}║${N}"
    echo -e "${C}╚══════════════════════════════════════════╝${N}"
    echo ""

    # Check if running
    if [ -f "/data/local/tmp/nfqws2.pid" ]; then
        local pid=$(cat /data/local/tmp/nfqws2.pid)
        if [ -d "/proc/$pid" ]; then
            echo -e "  Status: ${G}● RUNNING${N} (PID: $pid)"
        else
            echo -e "  Status: ${R}● STOPPED${N} (stale PID)"
        fi
    else
        echo -e "  Status: ${R}● STOPPED${N}"
    fi

    echo ""
    echo -e "${Y}Current Configuration:${N}"
    echo -e "  YouTube:  ${W}$STRATEGY_YOUTUBE${N}"
    echo -e "  Discord:  ${W}$STRATEGY_DISCORD${N}"
    echo -e "  Telegram: ${W}$STRATEGY_TELEGRAM${N}"
    echo -e "  Other:    ${W}$STRATEGY_OTHER${N}"
    echo -e "  UDP/QUIC: ${W}$STRATEGY_UDP${N}"

    echo ""
    echo -e "${Y}iptables Rules:${N}"
    local tcp_rules=$(iptables -t mangle -L OUTPUT -n 2>/dev/null | grep -c "NFQUEUE")
    local udp_rules=$(iptables -t mangle -L OUTPUT -n 2>/dev/null | grep -c "udp")
    echo -e "  TCP rules: ${W}$tcp_rules${N}"
    echo -e "  UDP rules: ${W}$udp_rules${N}"

    echo ""
    echo -e "${B}Press Enter to continue...${N}"
    read -r
}

##########################################################################################
# Main Menu
##########################################################################################

main_menu() {
    while true; do
        clear
        echo -e "${C}╔══════════════════════════════════════════╗${N}"
        echo -e "${C}║${W}     🛡️ ZAPRET2 DPI BYPASS MODULE 🛡️     ${C}║${N}"
        echo -e "${C}╠══════════════════════════════════════════╣${N}"

        # Status indicator
        if [ -f "/data/local/tmp/nfqws2.pid" ] && [ -d "/proc/$(cat /data/local/tmp/nfqws2.pid 2>/dev/null)" ]; then
            echo -e "${C}║${N}  Status: ${G}● RUNNING${N}                       ${C}║${N}"
        else
            echo -e "${C}║${N}  Status: ${R}● STOPPED${N}                       ${C}║${N}"
        fi

        echo -e "${C}╚══════════════════════════════════════════╝${N}"
        echo ""
        echo -e "${W}  [1]${N} 🎬 Configure YouTube Strategy"
        echo -e "${W}  [2]${N} 💬 Configure Discord Strategy"
        echo -e "${W}  [3]${N} ✈️  Configure Telegram Strategy"
        echo -e "${W}  [4]${N} 🌐 Configure Other Sites Strategy"
        echo -e "${W}  [5]${N} 📡 Configure UDP/QUIC Strategy"
        echo ""
        echo -e "${W}  [6]${N} ▶️  Start Zapret2"
        echo -e "${W}  [7]${N} ⏹️  Stop Zapret2"
        echo -e "${W}  [8]${N} 🔄 Restart Zapret2"
        echo ""
        echo -e "${W}  [9]${N} 📊 Show Status"
        echo -e "${W}  [0]${N} 💾 Save & Exit"
        echo ""
        echo -e "${B}Enter choice [0-9]:${N}"
        read -r choice

        case $choice in
            1) select_youtube_strategy ;;
            2) select_discord_strategy ;;
            3) select_telegram_strategy ;;
            4) select_other_strategy ;;
            5) select_udp_strategy ;;
            6)
                echo -e "${Y}Starting Zapret2...${N}"
                sh "$ZAPRET_DIR/scripts/zapret-start.sh"
                sleep 2
                ;;
            7)
                echo -e "${Y}Stopping Zapret2...${N}"
                sh "$ZAPRET_DIR/scripts/zapret-stop.sh"
                sleep 2
                ;;
            8)
                echo -e "${Y}Restarting Zapret2...${N}"
                sh "$ZAPRET_DIR/scripts/zapret-stop.sh"
                sleep 1
                sh "$ZAPRET_DIR/scripts/zapret-start.sh"
                sleep 2
                ;;
            9) show_status ;;
            0)
                save_config
                echo -e "${G}Goodbye!${N}"
                exit 0
                ;;
            *)
                echo -e "${R}Invalid choice!${N}"
                sleep 1
                ;;
        esac
    done
}

##########################################################################################
# Entry Point
##########################################################################################

# Load existing config
load_config

# Run main menu
main_menu
