#!/system/bin/sh
##########################################################################################
# Zapret2 Magisk Module - Action Menu (POSIX Compatible)
##########################################################################################

MODDIR="${0%/*}"
ZAPRET_DIR="$MODDIR/zapret2"
CONFIG="$ZAPRET_DIR/config.sh"

# Colors
R='\033[0;31m'
G='\033[0;32m'
Y='\033[0;33m'
B='\033[0;34m'
P='\033[0;35m'
C='\033[0;36m'
W='\033[0;37m'
N='\033[0m'

##########################################################################################
# Save Configuration
##########################################################################################

save_config() {
    cat > "$CONFIG" << EOF
#!/system/bin/sh
# Zapret2 Configuration - Generated by action.sh

AUTOSTART=1
QNUM=200
DESYNC_MARK=0x40000000
PORTS_TCP="80,443"
PORTS_UDP="443"
PKT_OUT=20
PKT_IN=10
LOG_MODE="android"

# Category Strategies
STRATEGY_YOUTUBE="$STRATEGY_YOUTUBE"
STRATEGY_DISCORD="$STRATEGY_DISCORD"
STRATEGY_TELEGRAM="$STRATEGY_TELEGRAM"
STRATEGY_OTHER="$STRATEGY_OTHER"
STRATEGY_UDP="$STRATEGY_UDP"

# Use category-based configuration
USE_CATEGORIES=1
EOF
    echo -e "${G}Configuration saved!${N}"
}

##########################################################################################
# Load Current Configuration
##########################################################################################

load_config() {
    if [ -f "$CONFIG" ]; then
        . "$CONFIG"
    fi

    # Defaults if not set
    STRATEGY_YOUTUBE="${STRATEGY_YOUTUBE:-syndata_7_tls_google_multisplit_midsld}"
    STRATEGY_DISCORD="${STRATEGY_DISCORD:-syndata_7_tls_google_multisplit_midsld}"
    STRATEGY_TELEGRAM="${STRATEGY_TELEGRAM:-none}"
    STRATEGY_OTHER="${STRATEGY_OTHER:-none}"
    STRATEGY_UDP="${STRATEGY_UDP:-none}"
}

##########################################################################################
# Strategy Selection Menus
##########################################################################################

select_youtube_strategy() {
    clear
    echo -e "${R}======================================${N}"
    echo -e "${R}       YOUTUBE STRATEGY${N}"
    echo -e "${R}======================================${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_YOUTUBE${N}"
    echo ""
    echo -e "  ${W}[1]${N} syndata_7_tls_google_multisplit_midsld (Default)"
    echo -e "  ${W}[2]${N} censorliber_google_syndata"
    echo -e "  ${W}[3]${N} censorliber_google_syndata_v2"
    echo -e "  ${W}[4]${N} censorliber_google_syndata_tcpack"
    echo -e "  ${W}[5]${N} alt9 (hostfakesplit)"
    echo -e "  ${W}[6]${N} alt11_100_syndata"
    echo -e "  ${W}[7]${N} none (Disabled)"
    echo ""
    echo -e "${B}Enter number [1-7] or 0 to cancel:${N}"
    read choice

    case "$choice" in
        1) STRATEGY_YOUTUBE="syndata_7_tls_google_multisplit_midsld" ;;
        2) STRATEGY_YOUTUBE="censorliber_google_syndata" ;;
        3) STRATEGY_YOUTUBE="censorliber_google_syndata_v2" ;;
        4) STRATEGY_YOUTUBE="censorliber_google_syndata_tcpack" ;;
        5) STRATEGY_YOUTUBE="alt9" ;;
        6) STRATEGY_YOUTUBE="alt11_100_syndata" ;;
        7) STRATEGY_YOUTUBE="none" ;;
        0|"") return ;;
        *) echo -e "${R}Invalid choice${N}"; sleep 1; return ;;
    esac
    echo -e "${G}YouTube strategy set to: $STRATEGY_YOUTUBE${N}"
    sleep 1
}

select_discord_strategy() {
    clear
    echo -e "${P}======================================${N}"
    echo -e "${P}       DISCORD STRATEGY${N}"
    echo -e "${P}======================================${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_DISCORD${N}"
    echo ""
    echo -e "  ${W}[1]${N} syndata_7_tls_google_multisplit_midsld (Default)"
    echo -e "  ${W}[2]${N} censorliber_google_syndata"
    echo -e "  ${W}[3]${N} fake_x6_stun_discord (Voice UDP)"
    echo -e "  ${W}[4]${N} none (Disabled)"
    echo ""
    echo -e "${B}Enter number [1-4] or 0 to cancel:${N}"
    read choice

    case "$choice" in
        1) STRATEGY_DISCORD="syndata_7_tls_google_multisplit_midsld" ;;
        2) STRATEGY_DISCORD="censorliber_google_syndata" ;;
        3) STRATEGY_DISCORD="fake_x6_stun_discord" ;;
        4) STRATEGY_DISCORD="none" ;;
        0|"") return ;;
        *) echo -e "${R}Invalid choice${N}"; sleep 1; return ;;
    esac
    echo -e "${G}Discord strategy set to: $STRATEGY_DISCORD${N}"
    sleep 1
}

select_telegram_strategy() {
    clear
    echo -e "${C}======================================${N}"
    echo -e "${C}       TELEGRAM STRATEGY${N}"
    echo -e "${C}======================================${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_TELEGRAM${N}"
    echo ""
    echo -e "  ${W}[1]${N} syndata_7_tls_google_multisplit_midsld (Default)"
    echo -e "  ${W}[2]${N} censorliber_google_syndata"
    echo -e "  ${W}[3]${N} none (Disabled)"
    echo ""
    echo -e "${B}Enter number [1-3] or 0 to cancel:${N}"
    read choice

    case "$choice" in
        1) STRATEGY_TELEGRAM="syndata_7_tls_google_multisplit_midsld" ;;
        2) STRATEGY_TELEGRAM="censorliber_google_syndata" ;;
        3) STRATEGY_TELEGRAM="none" ;;
        0|"") return ;;
        *) echo -e "${R}Invalid choice${N}"; sleep 1; return ;;
    esac
    echo -e "${G}Telegram strategy set to: $STRATEGY_TELEGRAM${N}"
    sleep 1
}

select_other_strategy() {
    clear
    echo -e "${G}======================================${N}"
    echo -e "${G}       OTHER SITES STRATEGY${N}"
    echo -e "${G}======================================${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_OTHER${N}"
    echo ""
    echo -e "  ${W}[1]${N} syndata_7_tls_google_multisplit_midsld (Default)"
    echo -e "  ${W}[2]${N} censorliber_google_syndata"
    echo -e "  ${W}[3]${N} multisplit_split_pos_1"
    echo -e "  ${W}[4]${N} other_seqovl"
    echo -e "  ${W}[5]${N} none (Disabled)"
    echo ""
    echo -e "${B}Enter number [1-5] or 0 to cancel:${N}"
    read choice

    case "$choice" in
        1) STRATEGY_OTHER="syndata_7_tls_google_multisplit_midsld" ;;
        2) STRATEGY_OTHER="censorliber_google_syndata" ;;
        3) STRATEGY_OTHER="multisplit_split_pos_1" ;;
        4) STRATEGY_OTHER="other_seqovl" ;;
        5) STRATEGY_OTHER="none" ;;
        0|"") return ;;
        *) echo -e "${R}Invalid choice${N}"; sleep 1; return ;;
    esac
    echo -e "${G}Other strategy set to: $STRATEGY_OTHER${N}"
    sleep 1
}

select_udp_strategy() {
    clear
    echo -e "${Y}======================================${N}"
    echo -e "${Y}       UDP/QUIC STRATEGY${N}"
    echo -e "${Y}======================================${N}"
    echo ""
    echo -e "Current: ${Y}$STRATEGY_UDP${N}"
    echo ""
    echo -e "  ${W}[1]${N} fake_x6_quic (QUIC Fake x6)"
    echo -e "  ${W}[2]${N} fake_x11_quic (QUIC Fake x11)"
    echo -e "  ${W}[3]${N} none (Disabled)"
    echo ""
    echo -e "${B}Enter number [1-3] or 0 to cancel:${N}"
    read choice

    case "$choice" in
        1) STRATEGY_UDP="fake_x6_quic" ;;
        2) STRATEGY_UDP="fake_x11_quic" ;;
        3) STRATEGY_UDP="none" ;;
        0|"") return ;;
        *) echo -e "${R}Invalid choice${N}"; sleep 1; return ;;
    esac
    echo -e "${G}UDP strategy set to: $STRATEGY_UDP${N}"
    sleep 1
}

##########################################################################################
# Status Display
##########################################################################################

show_status() {
    clear
    echo -e "${C}======================================${N}"
    echo -e "${C}       ZAPRET2 STATUS${N}"
    echo -e "${C}======================================${N}"
    echo ""

    # Check if running
    if [ -f "/data/local/tmp/nfqws2.pid" ]; then
        pid=$(cat /data/local/tmp/nfqws2.pid 2>/dev/null)
        if [ -d "/proc/$pid" ]; then
            echo -e "  Status: ${G}RUNNING${N} (PID: $pid)"
        else
            echo -e "  Status: ${R}STOPPED${N} (stale PID)"
        fi
    else
        echo -e "  Status: ${R}STOPPED${N}"
    fi

    echo ""
    echo -e "${Y}Current Configuration:${N}"
    echo -e "  YouTube:  ${W}$STRATEGY_YOUTUBE${N}"
    echo -e "  Discord:  ${W}$STRATEGY_DISCORD${N}"
    echo -e "  Telegram: ${W}$STRATEGY_TELEGRAM${N}"
    echo -e "  Other:    ${W}$STRATEGY_OTHER${N}"
    echo -e "  UDP/QUIC: ${W}$STRATEGY_UDP${N}"

    echo ""
    echo -e "${Y}iptables Rules:${N}"
    tcp_rules=$(iptables -t mangle -L OUTPUT -n 2>/dev/null | grep -c "NFQUEUE" || echo "0")
    echo -e "  NFQUEUE rules: ${W}$tcp_rules${N}"

    echo ""
    echo -e "${B}Press Enter to continue...${N}"
    read dummy
}

##########################################################################################
# Main Menu
##########################################################################################

main_menu() {
    while true; do
        clear
        echo -e "${C}======================================${N}"
        echo -e "${C}   ZAPRET2 DPI BYPASS MODULE${N}"
        echo -e "${C}======================================${N}"

        # Status indicator
        if [ -f "/data/local/tmp/nfqws2.pid" ]; then
            pid=$(cat /data/local/tmp/nfqws2.pid 2>/dev/null)
            if [ -d "/proc/$pid" ]; then
                echo -e "  Status: ${G}RUNNING${N}"
            else
                echo -e "  Status: ${R}STOPPED${N}"
            fi
        else
            echo -e "  Status: ${R}STOPPED${N}"
        fi

        echo -e "${C}======================================${N}"
        echo ""
        echo -e "  ${W}[1]${N} YouTube Strategy"
        echo -e "  ${W}[2]${N} Discord Strategy"
        echo -e "  ${W}[3]${N} Telegram Strategy"
        echo -e "  ${W}[4]${N} Other Sites Strategy"
        echo -e "  ${W}[5]${N} UDP/QUIC Strategy"
        echo ""
        echo -e "  ${W}[6]${N} Start Zapret2"
        echo -e "  ${W}[7]${N} Stop Zapret2"
        echo -e "  ${W}[8]${N} Restart Zapret2"
        echo ""
        echo -e "  ${W}[9]${N} Show Status"
        echo -e "  ${W}[0]${N} Save & Exit"
        echo ""
        echo -e "${B}Enter choice [0-9]:${N}"
        read choice

        case "$choice" in
            1) select_youtube_strategy ;;
            2) select_discord_strategy ;;
            3) select_telegram_strategy ;;
            4) select_other_strategy ;;
            5) select_udp_strategy ;;
            6)
                echo -e "${Y}Starting Zapret2...${N}"
                sh "$ZAPRET_DIR/scripts/zapret-start.sh"
                sleep 2
                ;;
            7)
                echo -e "${Y}Stopping Zapret2...${N}"
                sh "$ZAPRET_DIR/scripts/zapret-stop.sh"
                sleep 2
                ;;
            8)
                echo -e "${Y}Restarting Zapret2...${N}"
                sh "$ZAPRET_DIR/scripts/zapret-stop.sh"
                sleep 1
                sh "$ZAPRET_DIR/scripts/zapret-start.sh"
                sleep 2
                ;;
            9) show_status ;;
            0)
                save_config
                echo -e "${G}Goodbye!${N}"
                exit 0
                ;;
            *)
                echo -e "${R}Invalid choice!${N}"
                sleep 1
                ;;
        esac
    done
}

##########################################################################################
# Entry Point
##########################################################################################

# Load existing config
load_config

# Run main menu
main_menu
