#!/system/bin/sh
##########################################################################################
# Zapret2 Strategy Definitions
# Auto-generated by generate_module.py
# NOTE: --out-range is NOT included here - it is added dynamically from PKT_OUT config
##########################################################################################

LISTS_DIR="$ZAPRET_DIR/lists"

# Get strategy options by ID
get_strategy_options() {
    strategy_id="$1"
    filter="$2"

    case "$strategy_id" in
        # ==================== TCP STRATEGIES ====================
        syndata_2_tls_7)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls7"
            ;;

        syndata_3_tls_google)
            echo "$filter \
--lua-desync=send:repeats=3 \
--lua-desync=syndata:blob=tls_google"
            ;;

        syndata_7_n3)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls7"
            ;;

        syndata_multisplit_tls_google_700)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multisplit:seqovl=700:seqovl_pattern=tls_google:tcp_flags_unset=ack"
            ;;

        syndata_multidisorder_tls_google_700)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multidisorder:seqovl=700:seqovl_pattern=tls_google:tcp_flags_unset=ack"
            ;;

        syndata_multisplit_tls_google_1000)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multisplit:seqovl=1000:seqovl_pattern=tls_google"
            ;;

        syndata_multidisorder_tls_google_1000)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multidisorder:seqovl=1000:seqovl_pattern=tls_google:tcp_flags_unset=ack"
            ;;

        syndata_7_tls_google_multisplit_midsld)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multisplit:pos=midsld"
            ;;

        syndata_7_tls_max_ru_multisplit_midsld)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_max \
--lua-desync=multisplit:pos=midsld"
            ;;

        syndata_multidisorder_legacy_midsld)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multidisorder_legacy:pos=1,midsld"
            ;;

        alt9)
            echo "$filter \
--lua-desync=hostfakesplit:host=ozon.ru:tcp_ts=-1000:tcp_md5:repeats=4"
            ;;

        alt11_100_syndata)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ack=-66000 \
--lua-desync=fake:blob=tls_google:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:repeats=6:tcp_ack=-66000 \
--lua-desync=multisplit:pos=2:seqovl=652:seqovl_pattern=tls_google"
            ;;

        syndata_general_simple_fake_165_2)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ts=1000"
            ;;

        censorliber_google_syndata)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=fake:blob=tls_google:ip_ttl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=multidisorder:pos=1,midsld:seqovl=680:seqovl_pattern=tls_google:ip_ttl=-1,3-20:ip6_ttl=-1,3-20"
            ;;

        censorliber_google_syndata_v2)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multidisorder:pos=1,midsld:seqovl=680:seqovl_pattern=tls_google:tls_mod=rnd,rndsni,dupsid:ip_ttl=-1,3-20:ip6_ttl=-1,3-20"
            ;;

        censorliber_google_syndata_tcpack)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multidisorder:pos=1,midsld:seqovl=680:seqovl_pattern=tls_google:tls_mod=rnd,rndsni,dupsid:tcp_ack=-66000:ip_ttl=-1,3-20:ip6_ttl=-1,3-20"
            ;;

        censorliber_tls_google_syndata_tcpack_fake)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=fake:blob=tls_google:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:repeats=6:tcp_ack=-66000"
            ;;

        censorliber_tls_google_syndata_tcpack_fake_seqovl_1)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=fake:blob=tls_google:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:repeats=6:tcp_ack=-66000:seqovl=680:seqovl_pattern=tls_google"
            ;;

        censorliber_max_ru_syndata_tcpack_fake_seqovl_1)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_max \
--lua-desync=fake:blob=tls_max:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:repeats=6:tcp_ack=-66000:seqovl=680:seqovl_pattern=tls_max"
            ;;

        general_alt11_191_syndata)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=tls_max \
--lua-desync=fake:blob=tls_max:badsum:repeats=8 \
--lua-desync=multidisorder:pos=1:seqovl=681:seqovl_pattern=tls_max"
            ;;

        multidisorder_legacy_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder_legacy:pos=1,midsld"
            ;;

        multidisorder_legacy_seqovl_211)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder_legacy:seqovl=211:seqovl_pattern=tls5"
            ;;

        multidisorder_legacy_seqovl_652)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder_legacy:seqovl=652:seqovl_pattern=tls5"
            ;;

        multidisorder_legacy_badseq)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000 \
--lua-desync=multidisorder_legacy:pos=1,midsld:tcp_ack=-66000"
            ;;

        multidisorder_legacy_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_md5 \
--lua-desync=multidisorder_legacy:pos=1,midsld:tcp_md5"
            ;;

        multidisorder_legacy_syndata)
            echo "$filter \
--lua-desync=syndata \
--lua-desync=multidisorder_legacy:pos=1,midsld"
            ;;

        multidisorder_legacy_autottl)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder_legacy:pos=1,midsld:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multidisorder_legacy_sniext)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder_legacy:pos=sniext+1,midsld:seqovl=652"
            ;;

        other_seqovl)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=211:seqovl_pattern=tls5"
            ;;

        general_alt11_191)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:tcp_ts=1:repeats=8:payload=tls_client_hello \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_google:payload=tls_client_hello"
            ;;

        general_simplefake_alt2_191)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_max:tcp_ts=1:repeats=6"
            ;;

        general_simplefake_alt2_191_v2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_max:tcp_ts=1:repeats=6 \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_max:payload=tls_client_hello"
            ;;

        other_seqovl_v2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:seqovl=700:seqovl_pattern=tls_google:tcp_flags_unset=ack"
            ;;

        seqovl_211_google)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=211:seqovl_pattern=tls_google"
            ;;

        seqovl_211_tls4)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=211:seqovl_pattern=tls4"
            ;;

        seqovl_286_tls5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=286:seqovl_pattern=tls5"
            ;;

        seqovl_286_google)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=286:seqovl_pattern=tls_google"
            ;;

        seqovl_308_tls5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=308:seqovl_pattern=tls5"
            ;;

        seqovl_652_tls5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=652:seqovl_pattern=tls5"
            ;;

        seqovl_681_tls5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=681:seqovl_pattern=tls5"
            ;;

        seqovl_50_tls12)
            echo "$filter \
--lua-desync=multisplit:seqovl=50:seqovl_pattern=tls12"
            ;;

        seqovl_150_tls5)
            echo "$filter \
--lua-desync=multisplit:seqovl=150:seqovl_pattern=tls5"
            ;;

        seqovl_350_google)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=350:seqovl_pattern=tls_google"
            ;;

        seqovl_500_tls7)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=500:seqovl_pattern=tls7"
            ;;

        seqovl_211_tls9)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=211:seqovl_pattern=tls9"
            ;;

        multisplit_sniext_midsld_18)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=sniext+1,midsld:seqovl=652"
            ;;

        dis4_dup)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2 \
--lua-desync=multisplit:pos=2:seqovl=652:seqovl_pattern=tls_google"
            ;;

        dis4_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=midsld:seqovl=652:seqovl_pattern=tls_google"
            ;;

        multisplit_fake_tls_badseq)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2:tcp_ack=-66000:ip_autottl=0,3-20:ip6_autottl=0,3-20 \
--lua-desync=fake:blob=tls14:tcp_ack=-66000:ip_autottl=0,3-20:ip6_autottl=0,3-20:tls_mod=rnd,dupsid \
--lua-desync=multisplit:pos=sld+1:tcp_ack=-66000:ip_autottl=0,3-20:ip6_autottl=0,3-20"
            ;;

        multisplit_fake_tls_badseq_lite)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:tcp_ack=-66000:ip_autottl=0,3-20:ip6_autottl=0,3-20:tls_mod=rnd,dupsid \
--lua-desync=multisplit:pos=sld+1:tcp_ack=-66000:ip_autottl=0,3-20:ip6_autottl=0,3-20"
            ;;

        multisplit_fake_tls_badseq_autottl2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2:tcp_ack=-66000:ip_autottl=2,3-20:ip6_autottl=2,3-20 \
--lua-desync=fake:blob=tls14:tcp_ack=-66000:ip_autottl=2,3-20:ip6_autottl=2,3-20:tls_mod=rnd,dupsid \
--lua-desync=multisplit:pos=sld+1:tcp_ack=-66000:ip_autottl=2,3-20:ip6_autottl=2,3-20"
            ;;

        multisplit_fake_tls_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=fake:blob=tls1:tls_mod=rnd,dupsid:tcp_md5:ip_autottl=-1,3-20 \
--lua-desync=multisplit:pos=sld+1:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multisplit_fake_tls_md5sig_lite)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:tcp_md5:ip_autottl=0,3-20:ip6_autottl=0,3-20:tls_mod=rnd,dupsid \
--lua-desync=multisplit:pos=sld+1:tcp_md5:ip_autottl=0,3-20:ip6_autottl=0,3-20"
            ;;

        dronatar_4_2)
            echo "$filter \
--filter-l7=tls \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x00000000000000000000000000000000:repeats=6:tcp_ts_up"
            ;;

        dronatar_4_2_tlsmod)
            echo "$filter \
--filter-l7=tls \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:repeats=6:tls_mod=rnd,dupsid:tcp_ts_up"
            ;;

        multidisorder_badseq_pos)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000 \
--lua-desync=multidisorder:pos=1,midsld:tcp_ack=-66000"
            ;;

        multidisorder_md5sig_pos)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000:tcp_md5 \
--lua-desync=multidisorder:pos=1,midsld:tcp_ack=-66000:tcp_md5"
            ;;

        multidisorder_ipset_syndata)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=syndata:blob=syndata3:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        original_bolvan_v2_badsum)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:tcp_ack=-66000:repeats=6:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=multidisorder:pos=1,midsld:tcp_ack=-66000"
            ;;

        original_bolvan_v2_badsum_max)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000:tcp_ts_up:tls_mod=rnd,dupsid,sni=web.max.ru \
--lua-desync=multidisorder:pos=1,midsld"
            ;;

        multisplit_286_pattern)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=286:seqovl_pattern=tls11 \
--lua-desync=send:repeats=2"
            ;;

        multidisorder_super_split_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=15:ip_ttl=0:ip6_ttl=0:tcp_md5:badsum:tcp_ack=-66000:tcp_ts_up \
--lua-desync=multidisorder:pos=method+2,midsld,5"
            ;;

        multidisorder_super_split_badseq)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=15:ip_ttl=0:ip6_ttl=0:badsum:tcp_ack=-66000:tcp_ts_up \
--lua-desync=multidisorder:pos=method+2,midsld,5"
            ;;

        multidisorder_w3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=dtls_w3:tcp_ack=-66000:tcp_ts_up:tcp_md5 \
--lua-desync=multidisorder:pos=1,midsld"
            ;;

        multidisorder_pos_100)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=3:ip_ttl=4:ip6_ttl=4:tls_mod=rnd,dupsid \
--lua-desync=multidisorder:pos=100,midsld,sniext+1,endhost-2,-10"
            ;;

        dis14)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=midsld+1:seqovl=1"
            ;;

        multisplit_3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=midsld+1:seqovl=1:seqovl_pattern=tls7"
            ;;

        fake_badseq_rnd)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls7:tcp_ack=-66000:tcp_ts_up:tls_mod=rnd"
            ;;

        fakedsplit_badseq_4)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fakedsplit:pattern=tls4:pos=midsld-1,1:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        fake_autottl_faketls)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:ip_ttl=1:ip6_ttl=1:ip_autottl=4,3-20:ip6_autottl=4,3-20:tls_mod=rnd,rndsni,padencap"
            ;;

        fake_datanoack_fake_tls)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:tcp_flags_unset=ack:tls_mod=rnd,rndsni,padencap"
            ;;

        dis1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:tcp_flags_unset=ack:tls_mod=rnd,rndsni,padencap \
--lua-desync=fakeddisorder:pos=midsld:tcp_flags_unset=ack"
            ;;

        dis2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:ip_ttl=1:ip6_ttl=1:tls_mod=rnd,rndsni,padencap \
--lua-desync=multisplit:pos=1,midsld"
            ;;

        dis3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:repeats=10:tcp_ack=-66000:tcp_ts_up:ip_ttl=4:ip6_ttl=4"
            ;;

        dis5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ack=-66000:tcp_ts_up \
--lua-desync=multisplit"
            ;;

        dis5_sberbank)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_sber:repeats=6:ip_ttl=1:ip6_ttl=1:ip_autottl=5,3-20:ip6_autottl=5,3-20 \
--lua-desync=multisplit"
            ;;

        dis6)
            echo "$filter \
--lua-desync=syndata:blob=syndata3:ip_ttl=5:ip6_ttl=5"
            ;;

        dis7)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ack=-66000:tcp_ts_up:ip_autottl=2,3-20:ip6_autottl=2,3-20 \
--lua-desync=multisplit"
            ;;

        dis8)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls4:ip_ttl=4:ip6_ttl=4 \
--lua-desync=multisplit:pos=sniext:seqovl=1"
            ;;

        dis9)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:ip_ttl=2:ip6_ttl=2 \
--lua-desync=multisplit:pos=sniext:seqovl=1"
            ;;

        dis10)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=syndata:blob=tls_google:repeats=11:tcp_ack=-66000:tcp_ts_up \
--lua-desync=multidisorder:pos=3"
            ;;

        dis11)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:repeats=10:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        split_pos_badseq)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:repeats=10:tcp_ack=-66000:tcp_ts_up:ip_autottl=2,3-20:ip6_autottl=2,3-20"
            ;;

        dis12)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:repeats=10:tcp_ack=-66000:tcp_ts_up:ip_ttl=3:ip6_ttl=3"
            ;;

        dis13)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fakedsplit:pos=1:repeats=10:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        alt1_161)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ack=-66000:tcp_ts_up:ip_autottl=5,3-20:ip6_autottl=5,3-20 \
--lua-desync=multisplit:repeats=6:tcp_ack=-66000:tcp_ts_up:ip_autottl=5,3-20:ip6_autottl=5,3-20"
            ;;

        general_alt183)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ack=-66000:tcp_ts_up:ip_autottl=5,3-20:ip6_autottl=5,3-20 \
--lua-desync=fakedsplit:tcp_ack=-66000:tcp_ts_up:ip_autottl=5,3-20:ip6_autottl=5,3-20"
            ;;

        general_alt185)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ts=1000 \
--lua-desync=fakedsplit:pattern=0x00:tcp_ts=1000"
            ;;

        general_alt2183)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=2:seqovl=652:seqovl_pattern=tls_google"
            ;;

        general_alt3183_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fakedsplit:pos=1:repeats=8:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        general_alt4_182)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_md5 \
--lua-desync=multisplit:repeats=6:tcp_md5"
            ;;

        general_bf_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000:tcp_ts_up"
            ;;

        general_alt5_182)
            echo "$filter \
--ipcache-hostname \
--lua-desync=syndata"
            ;;

        general_alt6_182)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_google:repeats=2:tcp_ack=-66000:tcp_ts_up:ip6_hopbyhop2"
            ;;

        general_alt6_184)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_google"
            ;;

        general_alt7_184)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=2,sniext+1:seqovl=679:seqovl_pattern=tls_google"
            ;;

        general_alt8_185)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-2:tcp_ts_up"
            ;;

        fake_badseq_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-2"
            ;;

        general_alt8_185_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6"
            ;;

        general_alt8_185_3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-100000:tcp_ts_up"
            ;;

        fake_autottl_repeats_6_badseq)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:ip_autottl=2,3-20:ip6_autottl=2,3-20:repeats=6:tcp_ack=-66000"
            ;;

        general_simplefake_185)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ack=-10000000:tcp_ts_up"
            ;;

        altmgts2_161_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_md5"
            ;;

        general_simple_fake_165_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_ts=1000"
            ;;

        altmgts2_161_3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:ip_autottl=2,3-20:ip6_autottl=2,3-20:repeats=6:tcp_md5"
            ;;

        general_fake_tls_auto_alt_184)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=8:tcp_ack=-10000000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=fakedsplit:pos=1:tcp_ack=-10000000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        general_fake_tls_auto_alt_185)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=8:tcp_ack=-10000000:tcp_ts_up:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=fakedsplit:pos=1:tcp_ack=-10000000:tcp_ts_up"
            ;;

        general_fake_tls_auto_alt3_184)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=8:tcp_ts=1000:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_google:tcp_ts=1000"
            ;;

        general_fake_tls_auto_alt2_184)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=8:tcp_ack=-10000000:tcp_ts_up:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_google:tcp_ack=-10000000:tcp_ts_up"
            ;;

        general_fake_tls_auto_184)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=11:tcp_ack=-66000:tcp_ts_up:tls_mod=rnd,dupsid,sni=sun6-21.userapi.com \
--lua-desync=multidisorder:pos=1,midsld:tcp_ack=-66000:tcp_ts_up"
            ;;

        dronatar_4_3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000:tcp_ts_up:ip6_hopbyhop2"
            ;;

        launcher_zapret_2_9_1_v1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x0F0F0F0F:tcp_ack=-66000:tcp_ts_up:ip_autottl=2,2-12:ip6_autottl=2,2-12 \
--lua-desync=multidisorder:pos=7,sld+1:tcp_ack=-66000:tcp_ts_up:ip_autottl=2,2-12:ip6_autottl=2,2-12"
            ;;

        launcher_zapret_2_9_1_v1_tlsmod)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:tcp_ack=-66000:tcp_ts_up:ip_autottl=2,2-12:ip6_autottl=2,2-12:tls_mod=rnd,dupsid,sni=fonts.google.com \
--lua-desync=multidisorder:pos=7,sld+1:tcp_ack=-66000:tcp_ts_up:ip_autottl=2,2-12:ip6_autottl=2,2-12"
            ;;

        fake_md5sig_fake_tls)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:tcp_md5:tls_mod=rnd,rndsni,padencap"
            ;;

        launcher_zapret_2_9_1_v3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:pos=1,midsld:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        launcher_zapret_2_9_1_v4)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls4:repeats=2"
            ;;

        multidisorder_seqovl_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:pos=midsld-1:seqovl=1"
            ;;

        other_seqovl_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:seqovl=211:seqovl_pattern=tls5"
            ;;

        multisplit_226_pattern_18)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=226:seqovl_pattern=tls18 \
--lua-desync=send:repeats=2"
            ;;

        multisplit_226_pattern_google_Com)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:seqovl=226:seqovl_pattern=tls_google \
--lua-desync=send:repeats=2"
            ;;

        multisplit_308_pattern)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2 \
--lua-desync=multisplit:seqovl=308:seqovl_pattern=tls9"
            ;;

        multisplit_split_pos_1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1"
            ;;

        datanoack)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=pktmod:tcp_flags_unset=ack"
            ;;

        multisplit_datanoack)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:tcp_flags_unset=ack"
            ;;

        multisplit_datanoack_split_pos_1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:tcp_flags_unset=ack"
            ;;

        other_seqovl_fakedsplit_ttl2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x00000000:ip_ttl=2:ip6_ttl=2 \
--lua-desync=fakedsplit:pos=1:ip_ttl=2:ip6_ttl=2"
            ;;

        other_seqovl_fakedsplit_ttl2_tlsmod)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:ip_ttl=2:ip6_ttl=2:tls_mod=rnd,rndsni,dupsid \
--lua-desync=fakedsplit:pos=1:ip_ttl=2:ip6_ttl=2"
            ;;

        fakeddisorder_datanoack_1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x00000000:tcp_flags_unset=ack \
--lua-desync=fakeddisorder:pos=midsld:tcp_flags_unset=ack"
            ;;

        other_multidisorder)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_md5 \
--lua-desync=multidisorder:pos=1,midsld:tcp_md5"
            ;;

        fake_fakedsplit_autottl_2)
            echo "$filter \
--payload=http_req \
--lua-desync=fake:blob=fake_default_http:ip_autottl=2,3-20:ip6_autottl=2,3-20:tcp_ack=-66000:tcp_ts_up \
--lua-desync=fakedsplit:ip_autottl=2,3-20:ip6_autottl=2,3-20:tcp_ack=-66000:tcp_ts_up"
            ;;

        multisplit_seqovl_2_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x0F0F0F0F:tcp_md5 \
--lua-desync=multisplit:pos=1,midsld:seqovl=2:tcp_md5"
            ;;

        multisplit_17)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=fake:blob=tls17:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:tls_mod=rnd,dupsid \
--lua-desync=multisplit:pos=2,midsld:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        other5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_deepseek:tcp_flags_unset=ack \
--lua-desync=multidisorder:pos=midsld:tcp_flags_unset=ack"
            ;;

        multisplit_1_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1,midsld"
            ;;

        fake_multidisorder_1_split_pos_1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:badsum \
--lua-desync=multidisorder:pos=1:badsum"
            ;;

        multisplit_seqovl_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=midsld-1:seqovl=1"
            ;;

        bolvan_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=11:tcp_md5 \
--lua-desync=multidisorder:pos=1,midsld:tcp_md5"
            ;;

        bolvan_md5sig_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=11:tcp_md5:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=multidisorder:pos=1,midsld:tcp_md5"
            ;;

        bolvan_fake_tls)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls18:repeats=4:tcp_ack=-66000:tcp_ts_up \
--lua-desync=multidisorder:pos=1,midsld:tcp_ack=-66000:tcp_ts_up"
            ;;

        fake_multisplit_seqovl_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls4:tcp_md5:tcp_ack=-66000:tcp_ts_up:ip_ttl=2:ip6_ttl=2 \
--lua-desync=multisplit:pos=midsld-1:seqovl=1:tcp_md5:tcp_ack=-66000:tcp_ts_up"
            ;;

        multisplit_1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=sld+1:seqovl=1"
            ;;

        multisplit_2_plus)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=2,host,sld+1:seqovl=1"
            ;;

        multisplit_1_plus_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=sld+1:seqovl=1:seqovl_pattern=0x00"
            ;;

        multisplit_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=sld-1:seqovl=1"
            ;;

        multidisorder_fake_tls_1)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x0F0F0F0F:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=multidisorder:pos=7,sld+1:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multidisorder_fake_tls_1_tlsmod)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:tls_mod=rnd,dupsid,sni=fonts.google.com \
--lua-desync=multidisorder:pos=7,sld+1:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multidisorder_fake_tls_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=0x0F0F0F0F:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=multidisorder:pos=7,sld+1:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multidisorder_fake_tls_2_tlsmod)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls14:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:tls_mod=rnd,dupsid,sni=calendar.google.com \
--lua-desync=multidisorder:pos=7,sld+1:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        syndata)
            echo "$filter \
--lua-desync=syndata"
            ;;

        multisplit_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=fake:blob=tls9:tls_mod=rnd,dupsid:tcp_md5:ip_autottl=-1,3-20 \
--lua-desync=multisplit:pos=sld+1:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        fake_multidisorder_seqovl_fake_tls)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=2:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=fake:blob=tls9:tls_mod=rnd,dupsid:tcp_md5:ip_autottl=-1,3-20 \
--lua-desync=multidisorder:pos=sld+1:seqovl=1:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        syndata_md5sig_2)
            echo "$filter \
--ipcache-hostname \
--lua-desync=send:repeats=2:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=syndata:blob=tls7 \
--lua-desync=fake:blob=tls7:tls_mod=rnd,dupsid:tcp_md5:ip_autottl=-1,3-20 \
--lua-desync=multisplit:pos=sld+1:tcp_md5:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multisplit_seqovl_pos)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls2:ip_ttl=3:ip6_ttl=3 \
--lua-desync=multisplit:pos=3:seqovl=2"
            ;;

        multisplit_seqovl_pos_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls2n:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20:tls_mod=rnd \
--lua-desync=multisplit:pos=2:seqovl=2:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        multidisorder_repeats_md5sig)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=11:tcp_md5:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=multidisorder:pos=1,midsld:tcp_md5"
            ;;

        multidisorder_repeats_md5sig_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=11:tcp_md5 \
--lua-desync=multidisorder:pos=1,midsld:tcp_md5"
            ;;

        general_alt3183)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:repeats=8:tcp_ack=-66000:tcp_ts_up:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        general_alt4_161)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:repeats=6:tcp_md5 \
--lua-desync=multisplit:repeats=6:tcp_md5"
            ;;

        general_alt6_181)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:seqovl=681:seqovl_pattern=tls_google:repeats=2:tcp_ack=-66000:tcp_ts_up:ip6_hopbyhop2"
            ;;

        ankddev10)
            echo "$filter \
--ipcache-hostname \
--lua-desync=syndata:blob=tls_vk_kyber:tcp_md5 \
--lua-desync=multidisorder:pos=4:repeats=10:tcp_md5"
            ;;

        split2_seqovl_vk)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_vk:ip_ttl=2:ip6_ttl=2 \
--lua-desync=multisplit:pos=sniext:seqovl=625"
            ;;

        split2_seqovl_google)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:ip_ttl=4:ip6_ttl=4 \
--lua-desync=multisplit:pos=sniext:seqovl=1"
            ;;

        split2_split)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls \
--lua-desync=multisplit:pos=3:seqovl=2"
            ;;

        split2_seqovl_652)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls \
--lua-desync=multisplit:pos=3,midsld-1:seqovl=652:seqovl_pattern=tls4"
            ;;

        split2_split_google)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:ip_ttl=3:ip6_ttl=3 \
--lua-desync=multisplit:pos=3:seqovl=2"
            ;;

        split2_split_2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls2:ip_autottl=2,3-20:ip6_autottl=2,3-20 \
--lua-desync=multisplit:pos=3:seqovl=2"
            ;;

        fake_split2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls3:ip_ttl=2:ip6_ttl=2 \
--lua-desync=multisplit:pos=sniext:seqovl=1"
            ;;

        split_seqovl)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=sniext:seqovl=1:ip_ttl=1:ip6_ttl=1"
            ;;

        split_pos_badseq_10)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:repeats=10:tcp_ack=-66000:tcp_ts_up:ip_ttl=3:ip6_ttl=3"
            ;;

        split_pos_3)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=3:repeats=4:ip_autottl=1,3-20:ip6_autottl=1,3-20"
            ;;

        multidisorder_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:pos=1,midsld"
            ;;

        multidisorder_midsld_syndata)
            echo "$filter \
--lua-desync=syndata \
--lua-desync=multidisorder:pos=1,midsld"
            ;;

        googlevideo_fakedsplit)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fakedsplit:pos=1:tcp_ack=-66000:repeats=10:ip_ttl=4:ip6_ttl=4"
            ;;

        googlevideo_split)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:tcp_ack=-66000:repeats=10:ip_ttl=4:ip6_ttl=4"
            ;;

        googlevideo_multidisorder)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:pos=1,host+2,sld+2,sld+5,sniext+1,sniext+2,endhost-2:seqovl=1"
            ;;

        googlevideo_multisplit_pattern)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=2,midsld-2:seqovl=1:seqovl_pattern=tls7"
            ;;

        googlevideo_fakeddisorder)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fakeddisorder:pos=2,midsld-2:pattern=tls7:seqovl=1:tcp_ack=-66000:ip_autottl=0,3-20:ip6_autottl=0,3-20"
            ;;

        googlevideo_fakedsplit_simple)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fakedsplit:pos=1:tcp_ack=-66000:repeats=8:ip_autottl=0,3-20:ip6_autottl=0,3-20"
            ;;

        googlevideo_split_aggressive)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multisplit:pos=1:tcp_ack=-66000:repeats=15:ip_ttl=3:ip6_ttl=3"
            ;;

        googlevideo_multidisorder_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=multidisorder:pos=midsld,midsld+2:seqovl=1:tcp_ack=-66000:repeats=10"
            ;;

        googlevideo_fake_multisplit)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=tls_google:tcp_ack=-66000 \
--lua-desync=multisplit:pos=1,sld+1:seqovl=1:tcp_ack=-66000"
            ;;

        fake_fakedsplit_md5sig_80_port)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=1:tcp_md5 \
--lua-desync=fake:blob=fake_default_tls:tcp_md5:tcp_ack=-10000000:tcp_ts_up \
--lua-desync=fakedsplit:pos=midsld:tcp_md5:tcp_ack=-10000000:tcp_ts_up"
            ;;

        fake_multisplit_datanoack_wssize_midsld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=wssize:wsize=1:scale=6 \
--lua-desync=fake:blob=fake_default_tls:tcp_flags_unset=ack:tls_mod=rnd,dupsid,rndsni,padencap \
--lua-desync=multisplit:pos=midsld:tcp_flags_unset=ack"
            ;;

        syndata_1)
            echo "$filter \
--lua-desync=syndata:blob=tls4:ip_autottl=-1,3-20:ip6_autottl=-1,3-20"
            ;;

        syndata_4_badseq)
            echo "$filter \
--lua-desync=syndata:blob=tls4:tcp_ack=-66000:tcp_ts_up"
            ;;

        syndata_tls_google_5_repeats)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=5 \
--lua-desync=syndata:blob=tls_google"
            ;;

        syndata_tls_google_5_repeats_multidisorder)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=send:repeats=5 \
--lua-desync=syndata:blob=tls_google \
--lua-desync=multidisorder:pos=1,midsld:seqovl=800:seqovl_pattern=tls_google"
            ;;

        syndata_syn_packet_n3)
            echo "$filter \
--lua-desync=send:repeats=2 \
--lua-desync=syndata:blob=syn_packet"
            ;;

        tls_aggressive)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_aggressive:fakes=6:ttl_start=1:ttl_step=1:badseq:split_sni"
            ;;

        tls_aggressive_max)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_aggressive:fakes=11:ttl_start=1:ttl_step=2:seqovl=211:badseq:split_sni"
            ;;

        tls_aggressive_md5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_aggressive:fakes=6:ttl_start=1:md5sig:split_sni"
            ;;

        tls_multisplit_sni)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_multisplit_sni:seqovl=211"
            ;;

        tls_multisplit_sni_652)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_multisplit_sni:seqovl=652:seqovl_pattern=tls_google"
            ;;

        tls_fake_flood)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_flood:fakes=11:badseq"
            ;;

        tls_fake_flood_md5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_flood:fakes=11:md5sig"
            ;;

        tls_fake_flood_max)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_flood:fakes=20:pos=1,host,midsld,sld+1,endhost,sniext+1:badseq"
            ;;

        tls_combo_aggressive)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:ip_ttl=1:ip6_ttl=1:tcp_ack=-66000:tls_mod=rnd,dupsid,sni=www.google.com \
--lua-desync=tls_multisplit_sni:seqovl=211"
            ;;

        tls_fake_simple)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_simple:fakes=6:ttl=3"
            ;;

        tls_fake_only)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:ip_ttl=3:ip6_ttl=3:tls_mod=rnd,dupsid,sni=www.google.com"
            ;;

        tls_fake_only_ttl2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=8:ip_ttl=2:ip6_ttl=2:tls_mod=rnd,dupsid,sni=www.google.com"
            ;;

        tls_fake_only_badseq)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_ack=-66000:tls_mod=rnd,dupsid,sni=www.google.com"
            ;;

        tls_fake_only_md5)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=fake:blob=fake_default_tls:repeats=6:tcp_md5:tls_mod=rnd,dupsid,sni=www.google.com"
            ;;

        tls_pass)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=pass"
            ;;

        tls_fake_simple_ttl2)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_simple:fakes=6:ttl=2"
            ;;

        tls_fake_simple_10)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_simple:fakes=10:ttl=2"
            ;;

        tls_split_gentle)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_split_gentle:pos=midsld"
            ;;

        tls_split_gentle_host)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_split_gentle:pos=host"
            ;;

        tls_split_gentle_sld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_split_gentle:pos=sld+1"
            ;;

        tls_fake_split)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_split:fakes=4:ttl=2:pos=midsld"
            ;;

        tls_fake_split_host)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_split:fakes=4:ttl=2:pos=host"
            ;;

        tls_disorder_gentle)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_disorder_gentle"
            ;;

        tls_disorder_gentle_sld)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_disorder_gentle:pos1=sld:pos2=endhost"
            ;;

        tls_fake_disorder_gentle)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_disorder_gentle:fakes=3:ttl=2"
            ;;

        tls_fake_disorder_gentle_6)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=tls_fake_disorder_gentle:fakes=6:ttl=2"
            ;;

        censorliber_google)
            echo "$filter \
--lua-desync=multisplit_tls:payload=tls_client_hello:seqovl=680:sni=www.google.com:tls_mod=rnd,rndsni,dupsid:pos=2"
            ;;

        discord_window_collapse)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=discord_window_collapse:pos=host"
            ;;

        discord_router_alert)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=discord_router_alert:split=true"
            ;;

        discord_ecn_exploit)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=discord_ecn_exploit:disorder=true"
            ;;

        discord_timestamp_travel)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=discord_timestamp_travel:offset_sec=7200:split=true"
            ;;

        discord_urgent_sni)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=discord_urgent_sni:urgent_pos=midsld"
            ;;

        discord_ultimate_combo)
            echo "$filter \
--payload=tls_client_hello \
--lua-desync=discord_ultimate_combo:fakes=2:ttl=3:pos=host:pos2=endhost"
            ;;

        # ==================== UDP STRATEGIES ====================
        dronator_43)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=0x00"
            ;;

        fake_blob_quic_google_repeats_10_autottl)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:ip_autottl=-2,3-20:ip6_autottl=-2,3-20:payload=all:repeats=10"
            ;;

        fake_2_n2)
            echo "$filter \
--payload=all \
--lua-desync=fake:repeats=6"
            ;;

        fake_2_n2_google)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6"
            ;;

        fake_2_n2_test)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=2"
            ;;

        fake_4_google)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=4"
            ;;

        fake_4_quic1)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic1:repeats=4"
            ;;

        ipset_fake_6_d3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6"
            ;;

        general_bf_32)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=9:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=all"
            ;;

        ipset_fake_12_n2_apex)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=12:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=all"
            ;;

        ipset_fake_12_n3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=12:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=all"
            ;;

        ipset_fake_10_n2)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=10:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=all"
            ;;

        ipset_fake_14_n3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=14:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=all"
            ;;

        ipset_fake_tamper_11)
            echo "$filter \
--payload=dht \
--lua-desync=fake:blob=fake_default_quic:repeats=11:ip_autottl=2,3-20:ip6_autottl=2,3-20:payload=all \
--lua-desync=dht_dn:dn=2"
            ;;

        ipset_fake_quic6_ttl7)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic6:repeats=2:ip_ttl=7:ip6_ttl=7:payload=all"
            ;;

        fake_2_n2_test_2)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_test:repeats=2:payload=all"
            ;;

        fake_11_simple)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=fake_default_quic:repeats=11:payload=all"
            ;;

        fake_15_ttl0_md5sig)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=15:ip_ttl=0:ip6_ttl=0:badsum:payload=all"
            ;;

        fake_15_ttl0_badsum)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=15:ip_ttl=0:ip6_ttl=0:badsum:payload=all"
            ;;

        fake_6_google)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6:payload=all"
            ;;

        fake_ipfrag2_quic5)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic5:repeats=3:payload=all \
--lua-desync=send:ipfrag:ipfrag_pos_udp=8 \
--lua-desync=drop"
            ;;

        fake_ipfrag2_quic3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic3:repeats=2:payload=all \
--lua-desync=send:ipfrag:ipfrag_pos_udp=8 \
--lua-desync=drop"
            ;;

        fake_ipfrag2_quic7)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic7:repeats=3 \
--lua-desync=send:ipfrag:ipfrag_pos_udp=8 \
--lua-desync=drop"
            ;;

        fake_udplen_2_quic3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic3:repeats=2 \
--lua-desync=udplen:increment=2"
            ;;

        fake_udplen_4_quic3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic3:repeats=2 \
--lua-desync=udplen:increment=4"
            ;;

        fake_udplen_4_quic4)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic4:repeats=2 \
--lua-desync=udplen:increment=4"
            ;;

        fake_udplen_8_pattern1)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic6:repeats=2 \
--lua-desync=udplen:increment=8:pattern=0x0F0F0E0F"
            ;;

        fake_udplen_8_pattern1_autottl)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic6:repeats=2:ip_autottl=-1,3-20:ip6_autottl=-1,3-20 \
--lua-desync=udplen:increment=8:pattern=0x0F0F0E0F"
            ;;

        fake_udplen_8_pattern2)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic7:repeats=2 \
--lua-desync=udplen:increment=8:pattern=0x0E0F0E0F"
            ;;

        fake_udplen_8_pattern3)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic4:repeats=2 \
--lua-desync=udplen:increment=8:pattern=0xFEA82025"
            ;;

        fake_udplen_25)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic5:repeats=2 \
--lua-desync=udplen:increment=25"
            ;;

        fake_udplen_25_10)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=10 \
--lua-desync=udplen:increment=25"
            ;;

        fake_tamper_11)
            echo "$filter \
--payload=dht \
--lua-desync=fake:blob=quic_google:repeats=11 \
--lua-desync=dht_dn:dn=2"
            ;;

        fake_tamper_11_autottl)
            echo "$filter \
--payload=dht \
--lua-desync=fake:blob=fake_default_quic:repeats=11:ip_autottl=2,3-20:ip6_autottl=2,3-20 \
--lua-desync=dht_dn:dn=2"
            ;;

        fake_6_n15_unknown)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6"
            ;;

        fake_11_quic_bin)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=11"
            ;;

        fake_2_n2_quic)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=2"
            ;;

        fake_repeat_2_quic)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=fake_quic:repeats=2"
            ;;

        fake_4_google_quic)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=4"
            ;;

        fake_6_google_quic)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6"
            ;;

        fake_6_1)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic1:repeats=6"
            ;;

        fake_6_vk_com)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_vk:repeats=6"
            ;;

        fake_8_google)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=8"
            ;;

        fake_10_pattern)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6 \
--lua-desync=udplen:increment=10:pattern=0xDEADBEEF"
            ;;

        fake_udplen)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic2:repeats=7 \
--lua-desync=udplen:increment=5:pattern=0xDEADBEEF"
            ;;

        fake_updlen_7_quic_cutoff)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_test:repeats=7 \
--lua-desync=udplen:increment=10:pattern=0xDEADBEEF"
            ;;

        fake_updlen_7_quic_google)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=7 \
--lua-desync=udplen:increment=10:pattern=0xDEADBEEF"
            ;;

        fake_updlen_10_pattern)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic2:repeats=8 \
--lua-desync=udplen:increment=10:pattern=0xDEADBEEF"
            ;;

        fake_udplen_6_pattern)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=6 \
--lua-desync=udplen:increment=10:pattern=0xDEADBEEF"
            ;;

        fake_udplen_11)
            echo "$filter \
--payload=all \
--lua-desync=fake:blob=quic_google:repeats=11 \
--lua-desync=udplen:increment=15"
            ;;

        *)
            echo ""
            ;;
    esac
}