#!/usr/bin/env python3
"""
Конвертер стратегий из txt формата в shell скрипт и WebUI HTML
"""

import re
import os
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict, Optional

@dataclass
class Strategy:
    id: str
    name: str
    author: str = ""
    label: str = ""
    description: str = ""
    blobs: List[str] = field(default_factory=list)
    options: List[str] = field(default_factory=list)
    protocol: str = "tcp"  # tcp or udp

def parse_strategies_file(filepath: str, protocol: str = "tcp") -> List[Strategy]:
    """Парсит файл стратегий в формате txt"""
    strategies = []
    current: Optional[Strategy] = None

    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')

            # Новая стратегия
            if line.startswith('[') and line.endswith(']'):
                if current:
                    strategies.append(current)
                strategy_id = line[1:-1]
                current = Strategy(id=strategy_id, name=strategy_id, protocol=protocol)
                continue

            if not current:
                continue

            # Метаданные
            if ' = ' in line and not line.startswith('--'):
                key, value = line.split(' = ', 1)
                key = key.strip()
                value = value.strip()

                if key == 'name':
                    current.name = value
                elif key == 'author':
                    current.author = value
                elif key == 'label':
                    current.label = value
                elif key == 'description':
                    current.description = value
                elif key == 'blobs':
                    current.blobs = [b.strip() for b in value.split(',')]

            # Опции nfqws2
            elif line.startswith('--'):
                current.options.append(line)

    if current:
        strategies.append(current)

    return strategies

def generate_shell_case(strategy: Strategy) -> str:
    """Генерирует case для shell скрипта"""
    # Фильтруем опции - убираем --filter-*, --payload для TCP (добавляется снаружи)
    opts = []
    for opt in strategy.options:
        # Пропускаем фильтры для TCP - они добавляются снаружи
        if strategy.protocol == "tcp" and opt.startswith('--filter-'):
            continue
        # Для UDP оставляем --payload
        opts.append(opt)

    if not opts:
        return ""

    # Форматируем опции
    opts_str = " \\\n".join(opts)

    return f'''        {strategy.id})
            echo "$filter \\
{opts_str}"
            ;;
'''

def generate_shell_script(tcp_strategies: List[Strategy], udp_strategies: List[Strategy]) -> str:
    """Генерирует полный shell скрипт strategies.sh"""

    # Группируем TCP стратегии
    tcp_cases = []
    for s in tcp_strategies:
        case = generate_shell_case(s)
        if case:
            tcp_cases.append(case)

    # Группируем UDP стратегии
    udp_cases = []
    for s in udp_strategies:
        case = generate_shell_case(s)
        if case:
            udp_cases.append(case)

    script = '''#!/system/bin/sh
##########################################################################################
# Zapret2 Strategy Definitions
# Auto-generated by convert_strategies.py
# Each function returns nfqws2 options for specific strategy
##########################################################################################

# Get strategy options by ID
get_strategy_options() {
    strategy_id="$1"
    filter="$2"  # e.g., "--filter-tcp=443 --filter-l7=tls"

    case "$strategy_id" in
        # ==================== TCP STRATEGIES ====================
'''

    script += '\n'.join(tcp_cases)

    script += '''
        # ==================== UDP STRATEGIES ====================
'''

    script += '\n'.join(udp_cases)

    script += '''
        # ==================== DISABLED ====================
        none|disabled|"")
            echo ""
            ;;

        *)
            # Unknown strategy - return empty
            echo ""
            ;;
    esac
}

# Get HTTP filter for category
get_http_filter() {
    category="$1"

    case "$category" in
        youtube)
            echo "--filter-tcp=80 --filter-l7=http --hostlist=$LISTS_DIR/youtube.txt"
            ;;
        discord)
            echo "--filter-tcp=80 --filter-l7=http --hostlist=$LISTS_DIR/discord.txt"
            ;;
        telegram)
            echo "--filter-tcp=80 --filter-l7=http --hostlist=$LISTS_DIR/telegram.txt"
            ;;
        other)
            echo "--filter-tcp=80 --filter-l7=http --hostlist=$LISTS_DIR/other.txt"
            ;;
        *)
            echo "--filter-tcp=80 --filter-l7=http"
            ;;
    esac
}

# Get TLS filter for category
get_tls_filter() {
    category="$1"

    case "$category" in
        youtube)
            echo "--filter-tcp=443 --filter-l7=tls --hostlist=$LISTS_DIR/youtube.txt"
            ;;
        discord)
            echo "--filter-tcp=443 --filter-l7=tls --hostlist=$LISTS_DIR/discord.txt"
            ;;
        telegram)
            echo "--filter-tcp=443 --filter-l7=tls --hostlist=$LISTS_DIR/telegram.txt"
            ;;
        other)
            echo "--filter-tcp=443 --filter-l7=tls --hostlist=$LISTS_DIR/other.txt"
            ;;
        *)
            echo "--filter-tcp=443 --filter-l7=tls"
            ;;
    esac
}

# Get UDP filter for category
get_udp_filter() {
    category="$1"

    case "$category" in
        youtube)
            echo "--filter-udp=443 --filter-l7=quic"
            ;;
        discord)
            echo "--filter-udp=443 --filter-l7=quic"
            ;;
        discord_voice)
            echo "--filter-udp=19294-50100"
            ;;
        *)
            echo "--filter-udp=443 --filter-l7=quic"
            ;;
    esac
}
'''

    return script

def generate_html_options(strategies: List[Strategy], include_labels: List[str] = None) -> str:
    """Генерирует HTML options для select"""

    # Группируем по типам
    groups = {
        'Syndata': [],
        'Censorliber': [],
        'Alt': [],
        'Multisplit/Disorder': [],
        'Fake': [],
        'SeqOvl': [],
        'Dronatar': [],
        'Другие': []
    }

    for s in strategies:
        # Фильтруем по label если указано
        if include_labels and s.label and s.label not in include_labels:
            continue

        # Определяем группу
        sid = s.id.lower()
        if sid.startswith('syndata'):
            groups['Syndata'].append(s)
        elif sid.startswith('censorliber'):
            groups['Censorliber'].append(s)
        elif sid.startswith('alt'):
            groups['Alt'].append(s)
        elif 'multisplit' in sid or 'multidisorder' in sid or 'disorder' in sid:
            groups['Multisplit/Disorder'].append(s)
        elif sid.startswith('fake'):
            groups['Fake'].append(s)
        elif 'seqovl' in sid:
            groups['SeqOvl'].append(s)
        elif sid.startswith('dronatar') or sid.startswith('dronator'):
            groups['Dronatar'].append(s)
        else:
            groups['Другие'].append(s)

    html = ''
    for group_name, group_strategies in groups.items():
        if not group_strategies:
            continue

        html += f'                    <optgroup label="{group_name}">\n'
        for s in group_strategies:
            label_badge = ""
            if s.label == "recommended":
                label_badge = " ⭐"
            elif s.label == "game":
                label_badge = " 🎮"
            elif s.label == "experimental":
                label_badge = " 🧪"

            # Сокращаем имя если слишком длинное
            name = s.name[:40] + "..." if len(s.name) > 40 else s.name
            html += f'                        <option value="{s.id}">{name}{label_badge}</option>\n'
        html += '                    </optgroup>\n'

    return html

def generate_webui_html(tcp_strategies: List[Strategy], udp_strategies: List[Strategy]) -> str:
    """Генерирует полный HTML файл WebUI"""

    tcp_options = generate_html_options(tcp_strategies)
    udp_options = generate_html_options(udp_strategies)

    # Читаем шаблон или создаём новый
    html = '''<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>Zapret2</title>
    <style>
        :root {
            --bg: #121212;
            --surface: #1e1e1e;
            --surface2: #2a2a2a;
            --primary: #bb86fc;
            --secondary: #03dac6;
            --error: #cf6679;
            --success: #4caf50;
            --warning: #ff9800;
            --text: #ffffff;
            --text2: #b3b3b3;
            --text3: #666666;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            -webkit-tap-highlight-color: transparent;
        }

        body {
            font-family: 'Roboto', -apple-system, sans-serif;
            background: var(--bg);
            color: var(--text);
            min-height: 100vh;
            padding-bottom: 70px;
        }

        .tab-bar {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: var(--surface);
            display: flex;
            border-top: 1px solid var(--surface2);
            z-index: 100;
        }

        .tab-btn {
            flex: 1;
            padding: 12px 8px;
            background: none;
            border: none;
            color: var(--text3);
            font-size: 12px;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 4px;
            cursor: pointer;
            transition: all 0.2s;
        }

        .tab-btn.active { color: var(--primary); }
        .tab-btn:active { background: var(--surface2); }
        .tab-icon { font-size: 20px; }

        .tab-content {
            display: none;
            padding: 16px;
        }
        .tab-content.active { display: block; }

        .header {
            text-align: center;
            padding: 16px 0;
        }
        .header h1 {
            font-size: 20px;
            font-weight: 500;
        }

        .status-card {
            background: var(--surface);
            border-radius: 16px;
            padding: 20px;
            margin-bottom: 16px;
            text-align: center;
        }

        .status-indicator {
            display: inline-flex;
            align-items: center;
            gap: 10px;
            padding: 10px 20px;
            border-radius: 24px;
            font-size: 16px;
            font-weight: 500;
            margin-bottom: 16px;
        }

        .status-indicator.running { background: rgba(76, 175, 80, 0.15); color: var(--success); }
        .status-indicator.stopped { background: rgba(207, 102, 121, 0.15); color: var(--error); }
        .status-indicator.loading { background: rgba(255, 152, 0, 0.15); color: var(--warning); }

        .status-dot {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            background: currentColor;
        }
        .status-indicator.running .status-dot { animation: pulse 2s ease-in-out infinite; }

        @keyframes pulse {
            0%, 100% { opacity: 1; transform: scale(1); }
            50% { opacity: 0.6; transform: scale(0.9); }
        }

        .status-details {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 12px;
            text-align: left;
        }

        .status-item {
            background: var(--surface2);
            padding: 12px;
            border-radius: 10px;
        }
        .status-item-label {
            font-size: 11px;
            color: var(--text3);
            text-transform: uppercase;
            margin-bottom: 4px;
        }
        .status-item-value {
            font-size: 14px;
            color: var(--text);
            font-weight: 500;
        }

        .card {
            background: var(--surface);
            border-radius: 16px;
            padding: 20px;
            margin-bottom: 16px;
        }
        .card-title {
            font-size: 14px;
            font-weight: 500;
            color: var(--text2);
            margin-bottom: 16px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }

        .btn-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 12px;
        }

        .btn {
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            padding: 16px;
            border: none;
            border-radius: 12px;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
            position: relative;
            overflow: hidden;
        }
        .btn:disabled { opacity: 0.5; cursor: not-allowed; }
        .btn:active:not(:disabled) { transform: scale(0.97); }

        .btn-start { background: var(--success); color: #000; }
        .btn-stop { background: var(--error); color: #fff; }
        .btn-restart { background: var(--warning); color: #000; }
        .btn-update { background: var(--primary); color: #000; }
        .btn-secondary { background: var(--surface2); color: var(--text); }

        .btn-icon { font-size: 18px; }

        .btn-loading::after {
            content: '';
            position: absolute;
            width: 20px;
            height: 20px;
            border: 2px solid transparent;
            border-top-color: currentColor;
            border-radius: 50%;
            animation: spin 0.8s linear infinite;
        }
        .btn-loading span { visibility: hidden; }

        @keyframes spin { to { transform: rotate(360deg); } }

        .strategy-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 14px 0;
            border-bottom: 1px solid var(--surface2);
        }
        .strategy-row:last-child { border-bottom: none; }
        .strategy-label { font-size: 15px; }

        .strategy-select {
            background: var(--surface2);
            color: var(--text);
            border: none;
            border-radius: 8px;
            padding: 10px 12px;
            font-size: 12px;
            max-width: 200px;
            cursor: pointer;
        }
        .strategy-select:focus { outline: 2px solid var(--primary); }
        .strategy-select optgroup { font-weight: bold; color: var(--primary); }

        .logs-actions {
            display: flex;
            gap: 8px;
            flex-wrap: wrap;
            margin-bottom: 12px;
        }
        .btn-small { padding: 10px 14px; font-size: 13px; }
        .logs-count { font-size: 12px; color: var(--text3); margin-bottom: 8px; }

        .logs-box {
            background: var(--bg);
            border-radius: 10px;
            padding: 12px;
            height: calc(100vh - 280px);
            min-height: 300px;
            overflow-y: auto;
            font-family: 'JetBrains Mono', 'Fira Code', monospace;
            font-size: 11px;
            line-height: 1.6;
            color: var(--text2);
        }
        .log-line { padding: 2px 0; word-break: break-all; }
        .log-line.error { color: var(--error); }
        .log-line.info { color: var(--secondary); }
        .log-line.warn { color: var(--warning); }

        .toast {
            position: fixed;
            bottom: 80px;
            left: 50%;
            transform: translateX(-50%) translateY(100px);
            background: var(--surface);
            color: var(--text);
            padding: 14px 24px;
            border-radius: 12px;
            font-size: 14px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.4);
            transition: transform 0.3s ease;
            z-index: 1000;
            max-width: 90%;
            text-align: center;
        }
        .toast.show { transform: translateX(-50%) translateY(0); }
        .toast.error { border-left: 4px solid var(--error); }
        .toast.success { border-left: 4px solid var(--success); }

        .activity-log {
            margin-top: 12px;
            padding: 12px;
            background: var(--bg);
            border-radius: 10px;
            font-size: 12px;
            color: var(--text2);
            max-height: 120px;
            overflow-y: auto;
        }
        .activity-item { padding: 4px 0; display: flex; gap: 8px; }
        .activity-time { color: var(--text3); flex-shrink: 0; }
        .activity-msg { color: var(--text2); }
        .activity-msg.ok { color: var(--success); }
        .activity-msg.err { color: var(--error); }
        .activity-msg.warn { color: var(--warning); }
    </style>
</head>
<body>
    <!-- Tab 1: Control -->
    <div id="tab-control" class="tab-content active">
        <div class="header"><h1>Zapret2 DPI Bypass</h1></div>
        <div class="status-card">
            <div id="status-indicator" class="status-indicator loading">
                <span class="status-dot"></span>
                <span id="status-text">Проверка...</span>
            </div>
            <div class="status-details">
                <div class="status-item">
                    <div class="status-item-label">Версия</div>
                    <div class="status-item-value" id="val-version">-</div>
                </div>
                <div class="status-item">
                    <div class="status-item-label">PID</div>
                    <div class="status-item-value" id="val-pid">-</div>
                </div>
                <div class="status-item">
                    <div class="status-item-label">iptables</div>
                    <div class="status-item-value" id="val-iptables">-</div>
                </div>
                <div class="status-item">
                    <div class="status-item-label">Действие</div>
                    <div class="status-item-value" id="val-lastaction">-</div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Управление</div>
            <div class="btn-grid">
                <button class="btn btn-start" id="btn-start" onclick="doStart()">
                    <span class="btn-icon">▶</span><span>Запустить</span>
                </button>
                <button class="btn btn-stop" id="btn-stop" onclick="doStop()">
                    <span class="btn-icon">■</span><span>Остановить</span>
                </button>
                <button class="btn btn-restart" id="btn-restart" onclick="doRestart()">
                    <span class="btn-icon">↻</span><span>Перезапуск</span>
                </button>
                <button class="btn btn-update" id="btn-update" onclick="doUpdate()">
                    <span class="btn-icon">↓</span><span>Обновить</span>
                </button>
            </div>
            <div class="activity-log" id="activity-log">
                <div class="activity-item">
                    <span class="activity-time">--:--</span>
                    <span class="activity-msg">Ожидание...</span>
                </div>
            </div>
        </div>
    </div>

    <!-- Tab 2: Strategies -->
    <div id="tab-strategies" class="tab-content">
        <div class="header"><h1>Стратегии</h1></div>
        <div class="card">
            <div class="card-title">YouTube (TLS)</div>
            <div class="strategy-row">
                <span class="strategy-label">TCP 443</span>
                <select class="strategy-select" id="strat-youtube" onchange="saveStrategies()">
                    <option value="none">Выключено</option>
TCP_OPTIONS_PLACEHOLDER
                </select>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Discord</div>
            <div class="strategy-row">
                <span class="strategy-label">TLS (TCP)</span>
                <select class="strategy-select" id="strat-discord" onchange="saveStrategies()">
                    <option value="none">Выключено</option>
TCP_OPTIONS_PLACEHOLDER
                </select>
            </div>
            <div class="strategy-row">
                <span class="strategy-label">Voice (UDP)</span>
                <select class="strategy-select" id="strat-discord-voice" onchange="saveStrategies()">
                    <option value="none">Выключено</option>
UDP_OPTIONS_PLACEHOLDER
                </select>
            </div>
        </div>
        <div class="card">
            <div class="card-title">Telegram (TLS)</div>
            <div class="strategy-row">
                <span class="strategy-label">TCP 443</span>
                <select class="strategy-select" id="strat-telegram" onchange="saveStrategies()">
                    <option value="none">Выключено</option>
TCP_OPTIONS_PLACEHOLDER
                </select>
            </div>
        </div>
        <div class="card">
            <div class="card-title">QUIC/UDP</div>
            <div class="strategy-row">
                <span class="strategy-label">UDP 443</span>
                <select class="strategy-select" id="strat-udp" onchange="saveStrategies()">
                    <option value="none">Выключено</option>
UDP_OPTIONS_PLACEHOLDER
                </select>
            </div>
        </div>
        <button class="btn btn-restart" style="width:100%" onclick="doRestart()">
            <span class="btn-icon">↻</span><span>Применить (перезапуск)</span>
        </button>
    </div>

    <!-- Tab 3: Logs -->
    <div id="tab-logs" class="tab-content">
        <div class="header"><h1>Логи</h1></div>
        <div class="logs-actions">
            <button class="btn btn-secondary btn-small" onclick="loadLogs()">🔄 Обновить</button>
            <button class="btn btn-secondary btn-small" onclick="loadFullLogs()">📜 Все логи</button>
            <button class="btn btn-secondary btn-small" onclick="loadErrorLogs()">⚠️ Ошибки</button>
            <button class="btn btn-secondary btn-small" onclick="copyLogs()">📋 Копировать</button>
        </div>
        <div class="logs-count" id="logs-count">- строк</div>
        <div class="logs-box" id="logs-box"><div class="log-line">Загрузка...</div></div>
    </div>

    <!-- Tab Bar -->
    <div class="tab-bar">
        <button class="tab-btn active" onclick="switchTab('control')">
            <span class="tab-icon">🎛️</span><span>Управление</span>
        </button>
        <button class="tab-btn" onclick="switchTab('strategies')">
            <span class="tab-icon">⚡</span><span>Стратегии</span>
        </button>
        <button class="tab-btn" onclick="switchTab('logs')">
            <span class="tab-icon">📋</span><span>Логи</span>
        </button>
    </div>

    <div class="toast" id="toast"></div>

    <script>
        const MODDIR = '/data/adb/modules/zapret2';
        const CONFIG = MODDIR + '/zapret2/config.sh';
        const SCRIPTS = MODDIR + '/zapret2/scripts';
        const LOGFILE = '/data/local/tmp/zapret2.log';
        const PIDFILE = '/data/local/tmp/nfqws2.pid';

        let isRunning = false;
        let activityLog = [];
        let currentLogs = '';

        function switchTab(tabName) {
            document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
            document.querySelectorAll('.tab-btn').forEach(b => b.classList.remove('active'));
            document.getElementById('tab-' + tabName).classList.add('active');
            document.querySelectorAll('.tab-btn')[
                tabName === 'control' ? 0 : tabName === 'strategies' ? 1 : 2
            ].classList.add('active');
            if (tabName === 'logs') loadLogs();
        }

        async function run(cmd) {
            try {
                if (typeof ksu !== 'undefined' && ksu.exec) return await ksu.exec(cmd);
                throw new Error('KSU API not available');
            } catch (e) {
                logActivity('Ошибка: ' + e.message, 'err');
                return '';
            }
        }

        function logActivity(msg, type = '') {
            const now = new Date();
            const time = now.toTimeString().slice(0, 5);
            activityLog.unshift({ time, msg, type });
            if (activityLog.length > 20) activityLog.pop();
            renderActivity();
        }

        function renderActivity() {
            const el = document.getElementById('activity-log');
            el.innerHTML = activityLog.map(a =>
                `<div class="activity-item"><span class="activity-time">${a.time}</span><span class="activity-msg ${a.type}">${escapeHtml(a.msg)}</span></div>`
            ).join('');
        }

        function escapeHtml(text) {
            const div = document.createElement('div');
            div.textContent = text || '';
            return div.innerHTML;
        }

        function toast(msg, type = '') {
            const el = document.getElementById('toast');
            el.textContent = msg;
            el.className = 'toast show ' + type;
            setTimeout(() => el.classList.remove('show'), 3000);
        }

        function setLoading(btnId, loading) {
            const btn = document.getElementById(btnId);
            if (!btn) return;
            btn.classList.toggle('btn-loading', loading);
            btn.disabled = loading;
        }

        function setAllButtons(disabled) {
            ['btn-start', 'btn-stop', 'btn-restart', 'btn-update'].forEach(id => {
                const btn = document.getElementById(id);
                if (btn) btn.disabled = disabled;
            });
        }

        async function checkStatus() {
            const indicator = document.getElementById('status-indicator');
            const statusText = document.getElementById('status-text');
            try {
                const pidCheck = await run(`if [ -f ${PIDFILE} ]; then PID=$(cat ${PIDFILE}); if [ -d /proc/$PID ]; then echo "running:$PID"; else echo "dead"; fi; else echo "stopped"; fi`);
                const result = pidCheck.trim();
                if (result.startsWith('running:')) {
                    isRunning = true;
                    const pid = result.split(':')[1];
                    indicator.className = 'status-indicator running';
                    statusText.textContent = 'Работает';
                    document.getElementById('val-pid').textContent = pid;
                } else {
                    isRunning = false;
                    indicator.className = 'status-indicator stopped';
                    statusText.textContent = 'Остановлен';
                    document.getElementById('val-pid').textContent = '-';
                }
                const iptables = await run('iptables -t mangle -L OUTPUT -n 2>/dev/null | grep -c NFQUEUE || echo 0');
                document.getElementById('val-iptables').textContent = iptables.trim() + ' правил';
                const version = await run(`grep "^version=" ${MODDIR}/module.prop 2>/dev/null | cut -d= -f2`);
                document.getElementById('val-version').textContent = version.trim() || '-';
            } catch (e) {
                indicator.className = 'status-indicator stopped';
                statusText.textContent = 'Ошибка';
            }
        }

        async function loadConfig() {
            try {
                const cfg = await run(`cat ${CONFIG} 2>/dev/null`);
                if (!cfg) return;
                const match = (name) => { const m = cfg.match(new RegExp(name + '="([^"]*)"')); return m ? m[1] : null; };
                const youtube = match('STRATEGY_YOUTUBE');
                const discord = match('STRATEGY_DISCORD');
                const discordVoice = match('STRATEGY_DISCORD_VOICE');
                const telegram = match('STRATEGY_TELEGRAM');
                const udp = match('STRATEGY_UDP');
                if (youtube) document.getElementById('strat-youtube').value = youtube;
                if (discord) document.getElementById('strat-discord').value = discord;
                if (discordVoice) document.getElementById('strat-discord-voice').value = discordVoice;
                if (telegram) document.getElementById('strat-telegram').value = telegram;
                if (udp) document.getElementById('strat-udp').value = udp;
                logActivity('Конфиг загружен', 'ok');
            } catch (e) {
                logActivity('Ошибка загрузки конфига', 'err');
            }
        }

        async function saveStrategies() {
            const youtube = document.getElementById('strat-youtube').value;
            const discord = document.getElementById('strat-discord').value;
            const discordVoice = document.getElementById('strat-discord-voice').value;
            const telegram = document.getElementById('strat-telegram').value;
            const udp = document.getElementById('strat-udp').value;
            const config = `#!/system/bin/sh
AUTOSTART=1
QNUM=200
DESYNC_MARK=0x40000000
PORTS_TCP="80,443"
PORTS_UDP="443"
PKT_OUT=20
PKT_IN=10
LOG_MODE="android"
STRATEGY_YOUTUBE="${youtube}"
STRATEGY_DISCORD="${discord}"
STRATEGY_DISCORD_VOICE="${discordVoice}"
STRATEGY_TELEGRAM="${telegram}"
STRATEGY_OTHER="none"
STRATEGY_UDP="${udp}"
USE_CATEGORIES=1
`;
            try {
                await run(`cat > ${CONFIG} << 'ENDCFG'\\n${config}ENDCFG`);
                logActivity('Стратегии сохранены', 'ok');
                document.getElementById('val-lastaction').textContent = 'Сохранено';
                toast('Сохранено', 'success');
            } catch (e) {
                logActivity('Ошибка сохранения', 'err');
            }
        }

        async function doStart() {
            setLoading('btn-start', true); setAllButtons(true);
            logActivity('Запуск Zapret2...', 'warn');
            document.getElementById('val-lastaction').textContent = 'Запуск...';
            try {
                await run(`sh ${SCRIPTS}/zapret-start.sh 2>&1`);
                logActivity('Запущен', 'ok');
                toast('Zapret2 запущен', 'success');
                document.getElementById('val-lastaction').textContent = 'Запущен';
            } catch (e) {
                logActivity('Ошибка запуска: ' + e.message, 'err');
                toast('Ошибка запуска', 'error');
            }
            setLoading('btn-start', false); setAllButtons(false);
            setTimeout(checkStatus, 500);
        }

        async function doStop() {
            setLoading('btn-stop', true); setAllButtons(true);
            logActivity('Остановка Zapret2...', 'warn');
            document.getElementById('val-lastaction').textContent = 'Остановка...';
            try {
                await run(`sh ${SCRIPTS}/zapret-stop.sh 2>&1`);
                logActivity('Остановлен', 'ok');
                toast('Zapret2 остановлен', 'success');
                document.getElementById('val-lastaction').textContent = 'Остановлен';
            } catch (e) {
                logActivity('Ошибка остановки', 'err');
                toast('Ошибка остановки', 'error');
            }
            setLoading('btn-stop', false); setAllButtons(false);
            setTimeout(checkStatus, 500);
        }

        async function doRestart() {
            setLoading('btn-restart', true); setAllButtons(true);
            logActivity('Перезапуск...', 'warn');
            document.getElementById('val-lastaction').textContent = 'Перезапуск...';
            try {
                await run(`sh ${SCRIPTS}/zapret-stop.sh 2>&1`);
                logActivity('Остановлен', 'ok');
                await new Promise(r => setTimeout(r, 1000));
                await run(`sh ${SCRIPTS}/zapret-start.sh 2>&1`);
                logActivity('Запущен', 'ok');
                toast('Перезапущен', 'success');
                document.getElementById('val-lastaction').textContent = 'Перезапущен';
            } catch (e) {
                logActivity('Ошибка перезапуска', 'err');
                toast('Ошибка', 'error');
            }
            setLoading('btn-restart', false); setAllButtons(false);
            setTimeout(checkStatus, 500);
        }

        async function doUpdate() {
            setLoading('btn-update', true);
            logActivity('Проверка обновлений...', 'warn');
            document.getElementById('val-lastaction').textContent = 'Проверка...';
            try {
                const response = await run('curl -s --connect-timeout 10 https://api.github.com/repos/youtubediscord/magisk-zapret2/releases/latest 2>/dev/null');
                if (!response) throw new Error('Нет ответа от сервера');
                const tagMatch = response.match(/"tag_name"\\s*:\\s*"([^"]+)"/);
                if (tagMatch) {
                    const latest = tagMatch[1];
                    const current = document.getElementById('val-version').textContent;
                    if (latest && latest !== current) {
                        logActivity('Доступно: ' + latest, 'ok');
                        toast('Доступно обновление: ' + latest, 'success');
                        document.getElementById('val-lastaction').textContent = 'Есть ' + latest;
                    } else {
                        logActivity('Обновлений нет', 'ok');
                        toast('У вас последняя версия', 'success');
                        document.getElementById('val-lastaction').textContent = 'Актуально';
                    }
                } else throw new Error('Не удалось разобрать ответ');
            } catch (e) {
                logActivity('Ошибка: ' + e.message, 'err');
                toast('Не удалось проверить', 'error');
                document.getElementById('val-lastaction').textContent = 'Ошибка';
            }
            setLoading('btn-update', false);
        }

        async function loadLogs() {
            logActivity('Загрузка логов...', 'warn');
            try {
                const logs = await run(`tail -200 ${LOGFILE} 2>/dev/null || echo "Логов нет"`);
                renderLogs(logs);
            } catch (e) {
                logActivity('Ошибка загрузки логов', 'err');
            }
        }

        async function loadFullLogs() {
            logActivity('Загрузка полных логов...', 'warn');
            document.getElementById('logs-box').innerHTML = '<div class="log-line">Загрузка...</div>';
            try {
                let logs = await run(`cat ${LOGFILE} 2>/dev/null || echo "Логов нет"`);
                const errorLog = await run('cat /data/local/tmp/nfqws2-error.log 2>/dev/null');
                if (errorLog && errorLog.trim()) logs += '\\n\\n=== nfqws2-error.log ===\\n' + errorLog;
                renderLogs(logs);
                toast('Загружено ' + logs.split('\\n').length + ' строк', 'success');
            } catch (e) {
                logActivity('Ошибка загрузки', 'err');
            }
        }

        async function loadErrorLogs() {
            logActivity('Загрузка ошибок...', 'warn');
            try {
                let logs = await run(`grep -i "error\\\\|fail\\\\|warn\\\\|cannot\\\\|not found" ${LOGFILE} 2>/dev/null || echo "Ошибок не найдено"`);
                const errorLog = await run('cat /data/local/tmp/nfqws2-error.log 2>/dev/null');
                if (errorLog && errorLog.trim()) logs += '\\n\\n=== nfqws2-error.log ===\\n' + errorLog;
                renderLogs(logs);
            } catch (e) {
                logActivity('Ошибка загрузки', 'err');
            }
        }

        function renderLogs(logs) {
            const box = document.getElementById('logs-box');
            const countEl = document.getElementById('logs-count');
            currentLogs = logs || '';
            if (logs && logs.trim()) {
                const lines = logs.split('\\n').filter(l => l.trim());
                countEl.textContent = lines.length + ' строк';
                box.innerHTML = lines.map(line => {
                    let cls = '';
                    const lower = line.toLowerCase();
                    if (lower.includes('error') || lower.includes('fail') || lower.includes('cannot')) cls = 'error';
                    else if (lower.includes('warn')) cls = 'warn';
                    else if (line.includes('[INFO]') || line.includes('===') || lower.includes('success') || lower.includes('started')) cls = 'info';
                    return `<div class="log-line ${cls}">${escapeHtml(line)}</div>`;
                }).join('');
                box.scrollTop = box.scrollHeight;
            } else {
                box.innerHTML = '<div class="log-line">Логи пусты</div>';
                countEl.textContent = '0 строк';
            }
        }

        async function copyLogs() {
            if (!currentLogs || !currentLogs.trim()) { toast('Нечего копировать', 'error'); return; }
            try {
                if (navigator.clipboard && navigator.clipboard.writeText) {
                    await navigator.clipboard.writeText(currentLogs);
                } else {
                    const textArea = document.createElement('textarea');
                    textArea.value = currentLogs;
                    textArea.style.position = 'fixed';
                    textArea.style.left = '-9999px';
                    document.body.appendChild(textArea);
                    textArea.select();
                    document.execCommand('copy');
                    document.body.removeChild(textArea);
                }
                toast('Скопировано ' + currentLogs.split('\\n').length + ' строк', 'success');
                logActivity('Логи скопированы', 'ok');
            } catch (e) {
                toast('Ошибка копирования', 'error');
            }
        }

        async function init() {
            logActivity('Инициализация...', 'warn');
            await checkStatus();
            await loadConfig();
            logActivity('Готово', 'ok');
            setInterval(checkStatus, 10000);
        }

        if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
        else init();
    </script>
</body>
</html>
'''

    # Заменяем плейсхолдеры
    html = html.replace('TCP_OPTIONS_PLACEHOLDER', tcp_options)
    html = html.replace('UDP_OPTIONS_PLACEHOLDER', udp_options)

    return html

def main():
    # Пути
    base_dir = Path(__file__).parent.parent
    tcp_file = Path(r"H:\Privacy\zapret\json\strategies\builtin\tcp.txt")
    udp_file = Path(r"H:\Privacy\zapret\json\strategies\builtin\udp.txt")

    output_shell = base_dir / "zapret2" / "strategies.sh"
    output_html = base_dir / "webroot" / "index.html"

    print(f"Парсинг TCP стратегий из {tcp_file}...")
    tcp_strategies = parse_strategies_file(str(tcp_file), "tcp")
    print(f"  Найдено {len(tcp_strategies)} TCP стратегий")

    print(f"Парсинг UDP стратегий из {udp_file}...")
    udp_strategies = parse_strategies_file(str(udp_file), "udp")
    print(f"  Найдено {len(udp_strategies)} UDP стратегий")

    print(f"\nГенерация {output_shell}...")
    shell_content = generate_shell_script(tcp_strategies, udp_strategies)
    output_shell.parent.mkdir(parents=True, exist_ok=True)
    with open(output_shell, 'w', encoding='utf-8', newline='\n') as f:
        f.write(shell_content)
    print(f"  Записано {len(shell_content)} байт")

    print(f"\nГенерация {output_html}...")
    html_content = generate_webui_html(tcp_strategies, udp_strategies)
    output_html.parent.mkdir(parents=True, exist_ok=True)
    with open(output_html, 'w', encoding='utf-8') as f:
        f.write(html_content)
    print(f"  Записано {len(html_content)} байт")

    print("\nГотово!")
    print(f"  TCP стратегий: {len(tcp_strategies)}")
    print(f"  UDP стратегий: {len(udp_strategies)}")

if __name__ == "__main__":
    main()
