#!/usr/bin/env python3
"""
Generate Magisk module files from categories.txt and hostlists
"""

import os
import re
import shutil
from pathlib import Path

# Paths
SCRIPT_DIR = Path(__file__).parent
MODULE_DIR = SCRIPT_DIR.parent
ZAPRET_DIR = Path(r"H:\Privacy\zapret")

CATEGORIES_FILE = ZAPRET_DIR / "json" / "strategies" / "builtin" / "categories.txt"
LISTS_DIR = ZAPRET_DIR / "lists"
TCP_STRATEGIES = ZAPRET_DIR / "json" / "strategies" / "builtin" / "tcp.txt"
UDP_STRATEGIES = ZAPRET_DIR / "json" / "strategies" / "builtin" / "udp.txt"

OUTPUT_LISTS_DIR = MODULE_DIR / "zapret2" / "lists"
OUTPUT_WEBROOT = MODULE_DIR / "webroot"
OUTPUT_SCRIPTS = MODULE_DIR / "zapret2" / "scripts"


def parse_categories(filepath):
    """Parse categories.txt into list of category dicts"""
    categories = []
    current = None

    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue

            # Section header [name]
            if line.startswith('[') and line.endswith(']'):
                if current:
                    categories.append(current)
                current = {'id': line[1:-1]}
                continue

            # Key = value
            if '=' in line and current:
                key, value = line.split('=', 1)
                current[key.strip()] = value.strip()

        if current:
            categories.append(current)

    return categories


def parse_strategies(filepath):
    """Parse tcp.txt or udp.txt into dict of strategies"""
    strategies = {}
    current_id = None
    current_name = None
    current_lines = []

    with open(filepath, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.rstrip()

            # Section [id]
            if line.startswith('[') and line.endswith(']'):
                if current_id and current_lines:
                    strategies[current_id] = {
                        'name': current_name or current_id,
                        'options': '\n'.join(current_lines)
                    }
                current_id = line[1:-1]
                current_name = None
                current_lines = []
                continue

            if current_id:
                if line.startswith('name = '):
                    current_name = line[7:].strip()
                elif line.startswith('--') or line.startswith('-'):
                    current_lines.append(line)

        if current_id and current_lines:
            strategies[current_id] = {
                'name': current_name or current_id,
                'options': '\n'.join(current_lines)
            }

    return strategies


def copy_hostlists():
    """Copy needed hostlists to module"""
    OUTPUT_LISTS_DIR.mkdir(parents=True, exist_ok=True)

    needed_files = [
        'youtube.txt', 'discord.txt', 'telegram.txt', 'whatsapp.txt',
        'facebook.txt', 'instagram.txt', 'twitter.txt', 'github.txt',
        'steam.txt', 'twitch.txt', 'soundcloud.txt', 'rutracker.txt',
        'rutor.txt', 'speedtest.txt', 'google.txt', 'amazon.txt',
        'roblox.txt', 'itch.txt', 'claude.txt', 'other.txt',
        'russia-blacklist.txt',
        # IPsets
        'ipset-youtube.txt', 'ipset-discord.txt', 'ipset-telegram.txt',
        'ipset-googlevideo.txt', 'ipset-whatsapp.txt', 'ipset-facebook.txt',
        'ipset-instagram.txt', 'ipset-twitter.txt', 'ipset-github.txt',
        'ipset-steam.txt', 'ipset-twitch.txt', 'ipset-soundcloud.txt',
        'ipset-rutracker.txt', 'ipset-amazon.txt', 'ipset-roblox.txt',
        'ipset-anydesk.txt', 'ipset-warp.txt', 'ipset-claude.txt',
        'ipset-censorliber.txt',
    ]

    copied = 0
    for fname in needed_files:
        src = LISTS_DIR / fname
        dst = OUTPUT_LISTS_DIR / fname
        if src.exists():
            shutil.copy2(src, dst)
            copied += 1
            print(f"  Copied: {fname}")
        else:
            print(f"  Missing: {fname}")

    return copied


def generate_strategies_sh(tcp_strats, udp_strats):
    """Generate strategies.sh with all strategies"""

    lines = [
        '#!/system/bin/sh',
        '##########################################################################################',
        '# Zapret2 Strategy Definitions',
        '# Auto-generated by generate_module.py',
        '##########################################################################################',
        '',
        'LISTS_DIR="$ZAPRET_DIR/lists"',
        '',
        '# Get strategy options by ID',
        'get_strategy_options() {',
        '    strategy_id="$1"',
        '    filter="$2"',
        '',
        '    case "$strategy_id" in',
    ]

    # TCP strategies
    lines.append('        # ==================== TCP STRATEGIES ====================')
    for sid, sdata in tcp_strats.items():
        opts = sdata['options'].replace('\n', ' \\\n')
        lines.append(f'        {sid})')
        lines.append(f'            echo "$filter \\')
        lines.append(f'{opts}"')
        lines.append('            ;;')
        lines.append('')

    # UDP strategies
    lines.append('        # ==================== UDP STRATEGIES ====================')
    for sid, sdata in udp_strats.items():
        opts = sdata['options'].replace('\n', ' \\\n')
        lines.append(f'        {sid})')
        lines.append(f'            echo "$filter \\')
        lines.append(f'{opts}"')
        lines.append('            ;;')
        lines.append('')

    lines.append('        *)')
    lines.append('            echo ""')
    lines.append('            ;;')
    lines.append('    esac')
    lines.append('}')

    return '\n'.join(lines)


def generate_webui_html(categories, tcp_strats, udp_strats):
    """Generate index.html with all categories"""

    # Group categories by command_group
    groups = {}
    for cat in categories:
        group = cat.get('command_group', 'other')
        if group not in groups:
            groups[group] = []
        groups[group].append(cat)

    # Sort within groups by order
    for group in groups:
        groups[group].sort(key=lambda x: int(x.get('order', 999)))

    # Generate strategy options HTML
    def make_options(strat_type):
        strats = tcp_strats if strat_type in ('tcp', 'http80') else udp_strats
        opts = ['<option value="none">Выключено</option>']

        # Group by prefix
        current_group = None
        for sid, sdata in strats.items():
            name = sdata['name']
            # Truncate long names
            if len(name) > 45:
                name = name[:42] + '...'
            opts.append(f'<option value="{sid}">{name}</option>')

        return '\n                    '.join(opts)

    # Generate category cards
    cards_html = []

    # Define which categories to show (main ones for mobile)
    main_categories = [
        'youtube', 'youtube_udp', 'discord', 'discord_voice_udp',
        'telegram_tcp', 'whatsapp_tcp', 'facebook_tcp', 'instagram_tcp',
        'twitter_tcp', 'github_tcp', 'steam_tcp', 'twitch_tcp',
        'other'
    ]

    for cat in categories:
        cat_id = cat['id']
        if cat_id not in main_categories:
            continue

        full_name = cat.get('full_name', cat_id)
        protocol = cat.get('protocol', 'TCP')
        strat_type = cat.get('strategy_type', 'tcp')
        icon_color = cat.get('icon_color', '#666666')

        # Determine select ID
        select_id = f'strat-{cat_id.replace("_", "-")}'

        cards_html.append(f'''
        <div class="card">
            <div class="card-title" style="color: {icon_color}">{full_name}</div>
            <div class="strategy-row">
                <span class="strategy-label">{protocol}</span>
                <select class="strategy-select" id="{select_id}" onchange="saveStrategies()">
                    {make_options(strat_type)}
                </select>
            </div>
        </div>''')

    return '\n'.join(cards_html), main_categories


def generate_start_script(categories):
    """Generate category handling code for zapret-start.sh"""

    lines = []
    for cat in categories:
        cat_id = cat['id']
        var_name = f'STRATEGY_{cat_id.upper()}'
        base_filter = cat.get('base_filter_hostlist') or cat.get('base_filter_ipset') or cat.get('base_filter', '')
        strat_type = cat.get('strategy_type', 'tcp')

        lines.append(f'''
    # {cat.get('full_name', cat_id)}
    if [ -n "${var_name}" ] && [ "${var_name}" != "none" ]; then
        filter="{base_filter}"
        strat_opts=$(get_strategy_options "${var_name}" "$filter")
        if [ -n "$strat_opts" ]; then
            if [ $first -eq 0 ]; then
                OPTS="$OPTS --new"
            fi
            OPTS="$OPTS $strat_opts"
            first=0
            log_msg "Added {cat.get('full_name', cat_id)}: ${var_name}"
        fi
    fi''')

    return '\n'.join(lines)


def main():
    print("=" * 60)
    print("Zapret2 Magisk Module Generator")
    print("=" * 60)

    # Parse categories
    print("\n[1] Parsing categories.txt...")
    categories = parse_categories(CATEGORIES_FILE)
    print(f"    Found {len(categories)} categories")

    # Parse strategies
    print("\n[2] Parsing strategies...")
    tcp_strats = parse_strategies(TCP_STRATEGIES)
    udp_strats = parse_strategies(UDP_STRATEGIES)
    print(f"    TCP: {len(tcp_strats)}, UDP: {len(udp_strats)}")

    # Copy hostlists
    print("\n[3] Copying hostlists...")
    copied = copy_hostlists()
    print(f"    Copied {copied} files")

    # Generate strategies.sh
    print("\n[4] Generating strategies.sh...")
    strats_sh = generate_strategies_sh(tcp_strats, udp_strats)
    strats_path = MODULE_DIR / "zapret2" / "strategies.sh"
    with open(strats_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(strats_sh)
    print(f"    Written to {strats_path}")

    # Generate WebUI cards
    print("\n[5] Generating WebUI categories...")
    cards_html, main_cats = generate_webui_html(categories, tcp_strats, udp_strats)
    print(f"    Generated {len(main_cats)} category cards")
    print(f"    Categories: {', '.join(main_cats)}")

    # Generate start script additions
    print("\n[6] Generating start script code...")
    start_code = generate_start_script([c for c in categories if c['id'] in main_cats])

    # Save generated code for manual review
    gen_dir = MODULE_DIR / "tools" / "generated"
    gen_dir.mkdir(exist_ok=True)

    with open(gen_dir / "categories_html.txt", 'w', encoding='utf-8') as f:
        f.write(cards_html)

    with open(gen_dir / "start_script_code.txt", 'w', encoding='utf-8') as f:
        f.write(start_code)

    print(f"\n    Generated code saved to {gen_dir}")

    print("\n" + "=" * 60)
    print("DONE! Review generated files in tools/generated/")
    print("=" * 60)


if __name__ == '__main__':
    main()
